---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
  annotations:
    lbipam.cilium.io/ips: "192.168.30.203"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: oauth2-proxy
  ports:
    - name: http
      port: 4180
      targetPort: 4180
