---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kanidm-config
  namespace: kanidm
data:
  server.toml: |
    bindaddress = "0.0.0.0:8443"
    ldapbindaddress = "0.0.0.0:3636"
    trust_x_forward_for = true
    db_path = "/data/kanidm.db"
    tls_chain = "/certs/tls.crt"
    tls_key = "/certs/tls.key"
    domain = "kanidm.opnsense.internal"
    origin = "https://kanidm.opnsense.internal"
    log_level = "info"
