---
apiVersion: kaniop.rs/v1beta1
kind: KanidmGroup
metadata:
  name: grafana-users
  namespace: kanidm
spec:
  kanidmRef:
    name: kanidm
  # Kanidm group name (with underscores) is derived from metadata.name with hyphens→underscores

---
apiVersion: kaniop.rs/v1beta1
kind: KanidmGroup
metadata:
  name: longhorn-users
  namespace: kanidm
spec:
  kanidmRef:
    name: kanidm

---
apiVersion: kaniop.rs/v1beta1
kind: KanidmGroup
metadata:
  name: zot-users
  namespace: kanidm
spec:
  kanidmRef:
    name: kanidm

---
apiVersion: kaniop.rs/v1beta1
kind: KanidmGroup
metadata:
  name: hubble-users
  namespace: kanidm
spec:
  kanidmRef:
    name: kanidm

---
apiVersion: kaniop.rs/v1beta1
kind: KanidmGroup
metadata:
  name: kiali-users
  namespace: kanidm
spec:
  kanidmRef:
    name: kanidm
