---
apiVersion: kaniop.rs/v1beta1
kind: KanidmOAuth2Client
metadata:
  name: grafana
  namespace: kanidm
spec:
  kanidmRef:
    name: kanidm
  displayname: Grafana
  origin: https://grafana.opnsense.internal
  redirectUrl:
    - https://grafana.opnsense.internal/oauth2/callback
  image:
    url: https://raw.githubusercontent.com/develeap/homelab/main/infra/k8s/kanidm/logos/grafana.png

---
apiVersion: kaniop.rs/v1beta1
kind: KanidmOAuth2Client
metadata:
  name: longhorn
  namespace: kanidm
spec:
  kanidmRef:
    name: kanidm
  displayname: Longhorn
  origin: https://longhorn.opnsense.internal
  redirectUrl:
    - https://longhorn.opnsense.internal/oauth2/callback
  image:
    url: https://raw.githubusercontent.com/develeap/homelab/main/infra/k8s/kanidm/logos/longhorn.png

---
apiVersion: kaniop.rs/v1beta1
kind: KanidmOAuth2Client
metadata:
  name: zot
  namespace: kanidm
spec:
  kanidmRef:
    name: kanidm
  displayname: Zot
  origin: https://zot.opnsense.internal
  redirectUrl:
    - https://zot.opnsense.internal/oauth2/callback
  image:
    url: https://raw.githubusercontent.com/develeap/homelab/main/infra/k8s/kanidm/logos/zot.png

---
apiVersion: kaniop.rs/v1beta1
kind: KanidmOAuth2Client
metadata:
  name: hubble
  namespace: kanidm
spec:
  kanidmRef:
    name: kanidm
  displayname: Cilium Hubble
  origin: https://hubble.opnsense.internal
  redirectUrl:
    - https://hubble.opnsense.internal/oauth2/callback

---
apiVersion: kaniop.rs/v1beta1
kind: KanidmOAuth2Client
metadata:
  name: kiali
  namespace: kanidm
spec:
  kanidmRef:
    name: kanidm
  displayname: Kiali
  origin: https://kiali.opnsense.internal
  redirectUrl:
    - https://kiali.opnsense.internal/oauth2/callback
