---
apiVersion: kaniop.rs/v1beta1
kind: KanidmOAuth2Client
metadata:
  name: grafana
  namespace: kanidm
spec:
  kanidmRef:
    name: kanidm
  name: grafana
  displayName: Grafana
  origin: https://grafana.opnsense.internal
  redirectUris:
    - https://grafana.opnsense.internal/oauth2/callback

---
apiVersion: kaniop.rs/v1beta1
kind: KanidmOAuth2Client
metadata:
  name: longhorn
  namespace: kanidm
spec:
  kanidmRef:
    name: kanidm
  name: longhorn
  displayName: Longhorn
  origin: https://longhorn.opnsense.internal
  redirectUris:
    - https://longhorn.opnsense.internal/oauth2/callback

---
apiVersion: kaniop.rs/v1beta1
kind: KanidmOAuth2Client
metadata:
  name: zot
  namespace: kanidm
spec:
  kanidmRef:
    name: kanidm
  name: zot
  displayName: Zot
  origin: https://zot.opnsense.internal
  redirectUris:
    - https://zot.opnsense.internal/oauth2/callback

---
apiVersion: kaniop.rs/v1beta1
kind: KanidmOAuth2Client
metadata:
  name: hubble
  namespace: kanidm
spec:
  kanidmRef:
    name: kanidm
  name: hubble
  displayName: Cilium Hubble
  origin: https://hubble.opnsense.internal
  redirectUris:
    - https://hubble.opnsense.internal/oauth2/callback

---
apiVersion: kaniop.rs/v1beta1
kind: KanidmOAuth2Client
metadata:
  name: kiali
  namespace: kanidm
spec:
  kanidmRef:
    name: kanidm
  name: kiali
  displayName: Kiali
  origin: https://kiali.opnsense.internal
  redirectUris:
    - https://kiali.opnsense.internal/oauth2/callback
