---
apiVersion: kaniop.rs/v1beta1
kind: KanidmPersonAccount
metadata:
  name: lior
  namespace: kanidm
spec:
  kanidmRef:
    name: kanidm
  personAttributes:
    displayname: Lior Dux
    mail:
      - lior.dux@develeap.com
