defaultSettings:
  defaultDataPath: /var/mnt/longhorn
  defaultReplicaCount: 2
  storageOverProvisioningPercentage: 100
  storageMinimalAvailablePercentage: 10
  nodeDrainPolicy: block-if-contains-last-replica
  autoSalvage: true
  autoDeletePodWhenVolumeDetachedUnexpectedly: true
  allowVolumeCreationWithDegradedAvailability: true
  replicaSoftAntiAffinity: true
  orphanAutoDeletion: true
  concurrentReplicaRebuildPerNodeLimit: 1
  v2DataEngine: false
