apiVersion: ENC[AES256_GCM,data:H8c=,iv:Ozyzb09FmK7AP6C28ptzXhpVDwJeuQ8G3vyafTj41b4=,tag:x6Efi7C1cdrn3h0p6zoS4w==,type:str]
kind: ENC[AES256_GCM,data:jrkWLXnS,iv:XlUzWfKLYXfyuJGMs7kcvonjFWiTpZWnIAeFZXlI/ho=,tag:08BNc1N8hZg/8VEOKCRpgw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ahpi3FNmLSnmnexByLsU4rGIRnIgRF070vGpWw==,iv:fURazlZpRJW3jsA9q/OTegBtsbqxsflwKciZYsfMAtc=,tag:lEJ3BnpBvTC693AZFvAT2w==,type:str]
    namespace: ENC[AES256_GCM,data:3JAT+BztCJqpumCg,iv:8W1GkAjTI6Ub0ukD1H12FjQuqxiWzqlyCwr08nNy1S4=,tag:NaA5ILH9pPVhR2OJDaqkIw==,type:str]
stringData:
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:wnp1CekDvXy+dGaD/GYwQBLyj+LMSIhsCmTuLocTPs+1BICHq/hB/koy9dmK8kIt,iv:uLR7M8h/zf3TiFclNj68iyK6I5OjLNMtlOVMrf4ULYw=,tag:0V2mZTIek6ULOnFUSE3SXw==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:p2c43FisE/IxbZ2Wboes569HlO5EPIb8huarB+unhQ5ahR/vXO+HTS/bybQ=,iv:OmcNP5vKvZe5Tvm1kMJFqzgt46mSz8OSW9JTgWSdjLY=,tag:aF4FrbDiVVSbrExUQGILOw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IERqbWlOaHpw
            SkVwa0t1VFY2aTlqTHpwU0NmejgvYTU2WDdhYU8xWnBIMGJsVVBCNmFoQkVtRnhC
            OEhuMGwvUWsxdHVaWnZib0ttVFNwRU1qV0VIRzdZZzZ4c1NoS2VUazJLYnkvWVZT
            Z1o0VE9BU2xpV2I3RW9HNndyckRGUDVGeG5iVXFuRWxGNHd4U1hOU1pyTkV5QzEr
            LzBIZFRTbm1PU1pKZFlOVGIxMm5FK0g1WTRtQmM4OTJ5ejc4U2RYb2l0aDQ4Si80
            SEt0aDJDOW84cXA1bzN6TG9jYndDc1Y5WmpocU9QbXlxTktOb09oWXV3U0NoL25S
            SlJrOG1sMDFGWlFiYms1eW5NdHhBNXEraVNwTmZINGo5QVlQYkhid3RyeVRPenZZ
            V2ZnemtVRExmUEhYZlBtdDR3RUVoUnFTWGJhQm90K0E3eC94cElNdEJjT1lwNmVX
            S2xiUUhjenZmK1lOck9uWGtUeVdDOVZCVFBERnBqaU9SekpELzF5N3FaL3dCbVkv
            aW5YUHVqK01lTzVGM1RzYkxwams0T1kyd29NUzhXcmx4TitBWmY5UkxJLzFWVUZo
            Yko3OEcvdGVab1dHWnpzdzFWUEJON3ZNZUhub2tiQnhOZHUyNnVMYnZ4WnE0U0sz
            bEN3QUFXaEVjSmtQL25MQTRrUStwSWhFNVByZ3JxT0pJN3ladmZYcGtuTW1mT0JG
            dVUzWDR2TFQxTFlvVTRUbnRXY09LOW9zU0t6MmlLVWRTRkd6djRlaVZhUGVyOVZV
            aVpWa3o3Q0lQM0t3UDJ0NWNIL25qajZrTmFGZ1RXd1ZFcGYyNk53NFV3Um85L1V6
            WnVrbjZST1l3dXlMWHJ1aXBtUUgyRE4xaDlHM1JoL3dCQnBLMjBpYWVXdmpRRWV3
            dWxmN2dHVXJHQVloeVBERldGRFBxYTFNc0JhVUNhUXplQ2w0RWQ4bWFad0xwckh5
            alBlR2ZvbUFLVlJGMERsRnBWeGZ5U2wyWEUwZE9DTjBDRk1hTERIdVl4SlV3U0Jt
            ZDQ1MDZCMnkxVVpnMzlMYzhhRlFpUzZqRXBGRUxwK3R1a0hncEhnUytOaXJHNmFk
            a3pqaUQyZ3dhdGxzVklDSjA4QnhtcUUyemNEWjluYjd3UldQeXJ1UHVYYkplbGlJ
            cEc1VyszK3Z4amcvSE5SSmtHbndOUHRQdlRYQjhVVXJoa3kvWDdmbSs0R1RPbW52
            dkVwQnFpQ0FDMXg0UlF3VmhaWm5GL2E3ZGpTKyt4L2o3TDZ3bGNnNW5rYm1VT0lQ
            WFFiQTBjbW5YbTFIMnFVY2l6SnRVSmpqQmdZWVErbUYzSkFPSnJhT1VrWjM2NEcx
            dVFhVHBYSThhK3JZOC9KVGlIc3d1cnRCem93TzdNcVFGNFVBMUdoelUzQ3Y3QzFj
            aTMxSHpCd1pZSnJIR3FSRUphbjdsT0ZjYkRGbENETG1vV1crRStqc1EwT1g4dWt4
            bENxNC9iSDZKSm83TDRyTkttTjRDYytYL3JId2RWbDM5OU5WcWNxV0FxQ05YRE9E
            VFlJdUk4VGtHYUZzdmYwSStxejQybUVTZTZwK1ozZUVNOHl0ZVFHZTY1aWsranFR
            NEllY2ltMm92QkNLdXQxbXNGYytaVFN4QVhUNlZvcHFweXhaOGQ0UWpIb05ReHdX
            bXNkOHo3SXZXU09mOHlpeHE2S0hJQ0NqZDAwbkNPME9uU1RUR01QZGNUTkw5RVRB
            RWtManF2L0hidFpFK3lSTzRJMDBORUV1VkxsWjhnOU90S0dibUFTUHByT2h1b29v
            bUFIZ1Zad280TlpOR1ZsblZwc3QxY2plQVJnTzBmZ20vUHVPbjhTdGtaWXloc0JO
            QU01YXpCODNVRnlZUkRBMzBCYjE3bVpoY0l3TnRLWU8vdVdHUnExVEdqb29PSUwz
            T3kzcGlQNUJYRXJHY3JVNjNYa3ZBUmJCRDNFcDQ4SEdNSzdjTmhoZkd2MWVUUQpy
            QitjQXVlaGZIc0xsNkxuR1o0d2t6SUFtL3FpbmhyZ1lNUSsvd0VjQm5ZCi0tLSAz
            aUs5MUVxRlFwL3dPbTJSd1MySWZ3S3ByL0pvaE8yYmJpV1o4bEFCazRJCn0jfqzJ
            yWHM76IujdyIUYfP2WT0xvROspnRJSf8BGgVnCY01hlQeg13Czqm163nyVurh7sr
            1AecfU/c46yvdRA=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq182j3ewjp0rg2gfsanp9elcshzg9h5jpsqdxz24245fzz5fd366uksqvrq995x6kl0v53nevq4atfyhq53q98kl3sq4zf6uxpmh4sguvxwdg0p8dg6c6e45tjhymv63gnfltffzhsuf8gjhpp3l2caj75pgj7q8vtva25ejqckse8dxcmtxzryglf9dyqzst5mtcqaaenrhewk3rnp0z62kqrycrgyawgxn57t88mxxlpwv3tukryf9eh32vngzyeuzcvsa4za6kzf89qwxv3knmqhj9uzh9ds8n94yv8257q3dvluql30uy5ltgswgez5pxmkg6l2p53e7mn6xesy3ry48dez2ft2c23ewxde03mexfmc0mlsxu4q2n0qwxyreetz7npvjppzgmspqzlwf9gq7t3fcsu487xf06mas65kw9gru2skchuv9wcwzf89zhd52z8d44xu7sefxap2hqyyak8judkyzumvg2psxyvzmy8gkfz2qrz385xxljzwuut9vwwz2d6pd5044trh028fpqzcd8uuqwyv4gj8hv6vx3ktysgxw4tv9a83kae8mnqdcyvygfrtjedwrxgufv82ae5e8ru8txnxsmzadqaqy4yddpg7pjvw6gm437drvn9adv5mjnqx7wvjqj4tsmu0t99wwymel7g72qyvphygstan39f63z97azshhnreqdjrwc5j42e2xdwjyncq7vt9pe0y9qu43ywjacrw26zkfdvfnfvgmsxj967g6gd4xppem5m39smxzerkke8xcg4dzgxxgfg9f5peq0n6euzf6zsxj532k2cvlzc8q6m0t9x8gs8ll5gpvcnsmuq56stv5gru7d59uc3wpwfkespv3nec76jnyn7e79gzuevy96u2c2g7kg357ecv8qjge2sc6ragj9pq9yctev34djm5v02e2twkra7vs3rm6d7c2m6lcdkdm4pknkykc9quxtjrn9y5r42vg89jz49x3ga052wf2m6wglr5g7w53nzetzjudjx8ldxjgqp5c0yt9zfmx2zu76fkggn3rcugv035a0tzdyh79md77dh6kgqf9l5qrcrgk9cv9p9qks55ep8r9pcqnpmxcfy7ypr27zsh7upqle2kra6mv9aast4fe390sv3cv2hjdh3u4zf7upgqxg2wm9r0kswzhyt6rzjk33326vyk4amx92kzydnf9ccv0q6pcxg3nnp58tucw08fz6ym2d0ncvute9kgup7npd38x748egwdcv8czugdggg26uvl352w4znjcyze5u42xy8vc0fcajv0guhzq2vadfhcp4s0sz20dzntfw0hn6e4wm8h5ur5rq53g83ygxw4qez7amnnzf93skxmpdrc43v4en3au6z59y9xpsm9z3azv5thaxgph2fxewyx9d37r956g2nr5jn3msfqv4ssm2s39a3vcgd8sevl6deqysmhja5y2d5y0z7t0ak5xyfy4q557fxz2kgmgkq5mu60ya6eydfwzpf29vfklyll2f2de2hy2f79jx6xjwqt4fdxymyp2mcg7tw907hs2snfywfgagz5llfn4jd5pn74z6wtpgfqum4rssmpu2kqgtzyc3d4gcpqwdjsnwjzp4w2l5v9wnc6k5aw4q9z4wyencjtx3edwunfqn4tu9s2pqt8wl84y37qv5waukv78af0ywyz2redpmpkwzxu647gax95muz2s4fnydvtgh42vrlqqgulmt422zrjpmqvmxev5n7mku2tsmc599y2ym0sjwpacs8uztpzjyurgws390s2jxjzujw54usettx5uvf3q7wpqjkm55eqexddql87krt9wv2mnak5capzhk3lvs5ptafe9hex7v0znk76ma8yccuskv6y3stzzj2mh46w0cjmmuzf4yr96ecwtggvushzcltm3ss
    lastmodified: "2026-09-12T17:24:03Z"
    mac: ENC[AES256_GCM,data:ReLLhY0sZTnUi6zEWfHHls63HQvLuey6krS6yXrM876PMdNOlH/WnA/JsORgg/H7co6qTJExIXqT2UG6kBQrYLBxzMsFbUcfvrlgscj5n6y8GFotmQsY61qCQQaOQNep7c/W4A9T8214ON3zdA21Y8hXNu0eu6+BkxhozBdmw8k=,iv:+/TDjv2QoRSyH+D9bhvcVXNm0b5j+870jqnpqd9VDsU=,tag:tpoVVvZRJcsgZMe5n1vjXQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
