apiVersion: ENC[AES256_GCM,data:FAA=,iv:SRPuZNNMmCuFs4R4OrUHzf7NTaQaEgHRS/BZQIRQJLU=,tag:ZIjfLfwMZNzuoR2bJcecSw==,type:str]
kind: ENC[AES256_GCM,data:CeF7IZ3t,iv:jQPcCMUNed34jf53ST0bmq4JnP3QU4cMPJGgPVyQtis=,tag:b1R4UFtQjSyCRmMWB2P/LQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:FQvN2S9QeDPTxGkMvp81l3EGT6s=,iv:J2UX+qgWJrTXPkiqkqKNeRiKApW71kNuZX0ngVsZPpM=,tag:k0Ci0F7NY9svLS2t/tnAXA==,type:str]
    namespace: ENC[AES256_GCM,data:ax8hQGjbhhp6FNrL,iv:9ag5oHj8Sb2IyOW1NvKUnY9mzs8EA5GE9VVSjt3FfTo=,tag:VdrRzi79zhcO50wQf7oS+Q==,type:str]
stringData:
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:KBfO2v8e5xJsNHX39b/zD8xjvb/A+r+m8EZMtD86wQIFGfPkMioiURlTSAhDhMcp,iv:zjJ90Mo+enXb0M4inEOLlTc/muwgVziZcpgZ435kb+E=,tag:3Xph7eYRdqbQd61tcoGu6w==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:jeIyBPSEaBXe4SPnFQJvSea7uXPi7C5muVnr4LWC1ZM=,iv:JFgRVB2M5ih10cPtVNw8Fic3kp/x3AwYDQsfjjvDqAU=,tag:2JIJkz8YVLVaYajuqqo/gQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDQyM28wejdE
            WTVxdXRZWldXZURqdW5jcUZqOUllNTVEWmNVdFlWQjBUYUlNbEhxT2IvSGh2b1Rz
            TlBRMkpQcW9sSEthZVBiV08vNnIrWmc5cTFpTzVMTzdwd0twQlZMcndiYlNlTHgx
            S1pDUjRwMnJLZkdReEZqN1RzbXhBbEk2N01OelhUN3hUamJEK21ZM0xGc2NUS0Zq
            UXJ4bkk5ZlQ0MURYNkVaRFR4SHZjY2NZSTRGVHFFVnl5VTl6K0hIOUtMcWNndmIw
            d1dPZmZpSkJiSjBWYzdpblRzSzgxdmcvdFdVMmNpbmF1Q3BwVlhXaERnK0RZME5t
            TkpQU2Q2RCt6WEFRd1d2Wmp4VXl5cEg1MzY2aDQwZEtTdEFyeG5kcm4rbzlibWJ2
            SFZ1RE1saVJqQ1dhQ1ZoUHRocDNHYWd5aDRvRERxbTJBVE9XQ2I4dmd1YkEvM3dz
            NVg2WGFoMFZCbWtMa3dDckQ3RjNOTlBHYks4OXhYVVpTRXh3N0xMa0U5Q0NoOEpT
            S0lsQkNQdHIxd2htTGxyajV2V3ZwS0ZtMS9NeVYyNUZJUE5LVHBrUjZHWXN3disy
            TDM4Y1R3cnF0bDZWYStKc2lQQnhEUTU4Q3p5QWJDSkxPMmZpWFpIYUMzUTNEcGFT
            V0phdzV0ZjVUU3cvT0Y1TEZQYlRMS2REbk9QK055cURxM3RNMi9TVVdRNjFDZEZp
            Wmg0cWo1eEcvUmNRMFJuc2ZVdnFrVFB4Qlh0eDRNU0cyd01jQ29KNEllOUdDSUtj
            VUxIYmEvNFVURG8vQzZheFlpeE4zd3BQSTFPenNZR3NreHg0RU1Fb3lraHVxVk5Y
            UUpPUzZGOGpyVTBFSkZRSS94V0s1eW9aYU5kTTRCNHNPS1B2bGFob1BobGdlZFFJ
            Z1ZXQW8rbmMvUURMb1VodGZQRGsrdEg0Z2xta21vd1NtTUdkSzcyS0tKaEJTZXJv
            cVpGcDVsZ3dJU3IwdURHNVpHLzdkREFxamEzR2ZTMHVESG9KUlIvZ0VDWnZCOG9z
            VFdmUXFNbDlUV1ZXUko1dmp6ZXI2MDlkWVdmVE1QblZFbnRsSWRwelloNnA1cFVE
            SHdsRjZ4RWhudDZQT0N1b0crZVl5K0xFVGdPTkIxb3pEUWdJK0dSN0pjdkNXdFB4
            TEpvc1lYNEMyU0NXZ1l0NDlLTlhjNjdWeEFsdGdLSTdkSi9KcU5MN0JjdDB1c0Vp
            UmZURkIzeDBSNWxRK2lvWEFHVEU1UFMwZFR5N1FnaUIxYksrRm9iUEJ5KzdydWkv
            aW01cUZCeXppMFdzemp2emxCcVVsdDVKOHR6OXFmWEhXWGdwalR5ZURwZkJWa0s4
            YkEzYi9lQ080S1o2WnlaZFl4UTh1aFpGK0JPL3FoUDZNNk1LZ3ROVlptNjRrYzhD
            OThJaUZSY0lEWFc1R1RlTlRwdFFhMTdNS0NoTUsrK2JQNXdaK1hORVhSRzQyTkov
            Q25WNHhRQXJOT3lBWUl4Z0FtRVJJZVNqY1lxbjl2YUwrNWh0ZlBwNm0xTURsWmR0
            K0UzT1BoQ25adHhFalJQSzVPdCtYZHd0cmZ0aDFiVFgxTFFyVFRQeEdOVHpWd1FS
            Z2lSUkFocHhQbks2Skd2R0c1cjgySStGRlRXbkdIOUhvdnJmY0VETm9VM3h5MzVR
            MFhqQ2ZCRXlHSUVEMzBSVnhaeEIxek5YZGdCM1FVNmxSQmpyWCttc3cwSHlMUmtm
            cjlYMis0dUZoRUI5eGR6ZnBnb1VhSjNSUWllSW96andNeVZLT1lqMTdFS3pCUWtw
            a3dPZUFPN1NONHlCZk1qWHV5eHh4RVVtckJmUVdWSlJmaHNkSDZEbVE2bWxqbjJu
            bWhjS0ZDazlUM2FSWDBGUE8vVTdmazRrNWY4SjNKeHY4NC9GMHQ2ZFVCYlBEMG96
            WHZzMTBWbm9mMGd5d21rbTREbHByVEZVZGs1RFg0N0VXaUJPenU2b0hxNjhmZwpU
            Q2ZRdGxvd2ducS9oY1V0TytRVFEySlNPNjZJN1BzN0d4b2xZUUZyMUZFCi0tLSAv
            ZGRFQmxTZnNQTGhkend1QVN4c1NXc3dsVG91VkVpSWkwb1VDcUhYTS9RCqju6Htp
            ttzMHRxtjUi8wGhZUytuOj64HYVkRvsZiprRNgLoiMXOjT479TEw9NCO+/cpNogp
            5HYzPT59uDuQ5WM=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq182j3ewjp0rg2gfsanp9elcshzg9h5jpsqdxz24245fzz5fd366uksqvrq995x6kl0v53nevq4atfyhq53q98kl3sq4zf6uxpmh4sguvxwdg0p8dg6c6e45tjhymv63gnfltffzhsuf8gjhpp3l2caj75pgj7q8vtva25ejqckse8dxcmtxzryglf9dyqzst5mtcqaaenrhewk3rnp0z62kqrycrgyawgxn57t88mxxlpwv3tukryf9eh32vngzyeuzcvsa4za6kzf89qwxv3knmqhj9uzh9ds8n94yv8257q3dvluql30uy5ltgswgez5pxmkg6l2p53e7mn6xesy3ry48dez2ft2c23ewxde03mexfmc0mlsxu4q2n0qwxyreetz7npvjppzgmspqzlwf9gq7t3fcsu487xf06mas65kw9gru2skchuv9wcwzf89zhd52z8d44xu7sefxap2hqyyak8judkyzumvg2psxyvzmy8gkfz2qrz385xxljzwuut9vwwz2d6pd5044trh028fpqzcd8uuqwyv4gj8hv6vx3ktysgxw4tv9a83kae8mnqdcyvygfrtjedwrxgufv82ae5e8ru8txnxsmzadqaqy4yddpg7pjvw6gm437drvn9adv5mjnqx7wvjqj4tsmu0t99wwymel7g72qyvphygstan39f63z97azshhnreqdjrwc5j42e2xdwjyncq7vt9pe0y9qu43ywjacrw26zkfdvfnfvgmsxj967g6gd4xppem5m39smxzerkke8xcg4dzgxxgfg9f5peq0n6euzf6zsxj532k2cvlzc8q6m0t9x8gs8ll5gpvcnsmuq56stv5gru7d59uc3wpwfkespv3nec76jnyn7e79gzuevy96u2c2g7kg357ecv8qjge2sc6ragj9pq9yctev34djm5v02e2twkra7vs3rm6d7c2m6lcdkdm4pknkykc9quxtjrn9y5r42vg89jz49x3ga052wf2m6wglr5g7w53nzetzjudjx8ldxjgqp5c0yt9zfmx2zu76fkggn3rcugv035a0tzdyh79md77dh6kgqf9l5qrcrgk9cv9p9qks55ep8r9pcqnpmxcfy7ypr27zsh7upqle2kra6mv9aast4fe390sv3cv2hjdh3u4zf7upgqxg2wm9r0kswzhyt6rzjk33326vyk4amx92kzydnf9ccv0q6pcxg3nnp58tucw08fz6ym2d0ncvute9kgup7npd38x748egwdcv8czugdggg26uvl352w4znjcyze5u42xy8vc0fcajv0guhzq2vadfhcp4s0sz20dzntfw0hn6e4wm8h5ur5rq53g83ygxw4qez7amnnzf93skxmpdrc43v4en3au6z59y9xpsm9z3azv5thaxgph2fxewyx9d37r956g2nr5jn3msfqv4ssm2s39a3vcgd8sevl6deqysmhja5y2d5y0z7t0ak5xyfy4q557fxz2kgmgkq5mu60ya6eydfwzpf29vfklyll2f2de2hy2f79jx6xjwqt4fdxymyp2mcg7tw907hs2snfywfgagz5llfn4jd5pn74z6wtpgfqum4rssmpu2kqgtzyc3d4gcpqwdjsnwjzp4w2l5v9wnc6k5aw4q9z4wyencjtx3edwunfqn4tu9s2pqt8wl84y37qv5waukv78af0ywyz2redpmpkwzxu647gax95muz2s4fnydvtgh42vrlqqgulmt422zrjpmqvmxev5n7mku2tsmc599y2ym0sjwpacs8uztpzjyurgws390s2jxjzujw54usettx5uvf3q7wpqjkm55eqexddql87krt9wv2mnak5capzhk3lvs5ptafe9hex7v0znk76ma8yccuskv6y3stzzj2mh46w0cjmmuzf4yr96ecwtggvushzcltm3ss
    lastmodified: "2026-09-09T20:52:27Z"
    mac: ENC[AES256_GCM,data:kRTwe3HX4NwSyHqxWWVzkd8bf3SLeKyAOEUtlLIt3PgtAbUI8Nr+VKr45NBdCRn9SI0Uy7jMaQTfWWuRQjhW9hqU/K6s7pXXqIgoppkz20t7rVMvRVww3aDhZOuaalZxd+2m/bDXdksYZq2uV37epDvvh9+r+MkW29lxMHn/Ovc=,iv:x7cchdTsSnpVhqiqQWV84k4bJzP/i/336l9MjbB4A1I=,tag:70QUP8e1XDxlIOcv6+Ef7Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
