#ENC[AES256_GCM,data:MWAGmxKL9CEAyFzRp1/N9A00ZTSWZM1AaeCmxu3XcSw=,iv:IXhdY1Ut+3leqrR5vq3TylFcVueVK5UYmytyBmqZ4xg=,tag:cRomr7TSQB/CJ8CZke61fg==,type:comment]
#ENC[AES256_GCM,data:EcdbnYNXO1VAeJlCb2Ce2rBsHY6VGWHUZhZuLrSbpIisFnx2,iv:NupVzTMnkL1Euz/FFT9a1OHvPGuDQxcfF9dJ1Rtz9/E=,tag:6DG5vaWo40A8xJHiWkAfpg==,type:comment]
#ENC[AES256_GCM,data:Uc7PnxQNG/rEwQKispVWUfuoyBOQRhJWjXSvY4/Yr52nZ5f8pxOMdENlDIx9rF/wOSXr5RK5C8LdklFOOv2mGVseBqWjHikIigT2+hMsefIC1CwwtVKgZw==,iv:Ee5uQ6rmwhwADJYF5RMHP5NZX/nHPLzDcqcGH90Zn0w=,tag:PE5YlAacJv7KcmNhAhVK0A==,type:comment]
#ENC[AES256_GCM,data:DkUAc0msQ59/jrINoM9WtPOM,iv:8uEXLB6zwSAi9hI4eskTpYtlnec+06GX/1E6Sv9UpDI=,tag:80742Ry74fn1UnjIRis/vw==,type:comment]
#
#ENC[AES256_GCM,data:qSla6Ut6MF9QXao91SL88mO1nvRSICD4TqjjB2ULnqvYHMe/WC8B9z0O2rxwK81dOYXCADumjL8z/DioGpNbvG6cIJM=,iv:boogg2thEHC/IuhfWtaMxafTlWM87sKKUGenmg7PBsE=,tag:M7leZn2+Jr12Tq15fENWSg==,type:comment]
#ENC[AES256_GCM,data:WQ0bGs2vk+2ZvxXJcWy/iT2t03rdLyUnXsXKN1xvd8XjckmbOlvdr9FDf85BZZpBPbcFlmxPdOSbWNBFAHcDXj5N4q9skR8=,iv:RU75F1A6APbrnhs61prY4QTQi9rPqOwH3Aoex+apQpA=,tag:e5ZWh63MxZMXEAgJ1eG0dA==,type:comment]
#
#ENC[AES256_GCM,data:Y4GEx32Obr7NNdxlP0o+SyNjvZO24wXhf6RYGuB5,iv:OTxld8GmTKEN/j+L8A7E3ny7R6PuFDaQWUxYzXCC8kQ=,tag:we5Kftagw7Gw86klPKyL2g==,type:comment]
#ENC[AES256_GCM,data:RtqQW/jrFjgM1it7umrs8Rv1MDyjFptFD0PyyYB9TQJQp+P9AzS9oFs0BCeNI2BP,iv:VxbSyFgX4Db8ARXi8mvrhZM9Q8Z9xOpaOwIEH6hpv7Q=,tag:liAaBRwgjAARwHCA/brwBA==,type:comment]
apiVersion: ENC[AES256_GCM,data:gko=,iv:7SAj3UCtyq1BAB6QwNVu4kPZOEYH0w4aHUU60+7Le34=,tag:/kIAzEY65XY9TUTtP/ZUzg==,type:str]
kind: ENC[AES256_GCM,data:QM5QPeHX,iv:DPjmDGWWeZJd+VoJUR3CV3ehZ0PCvKWyr0SZJuCh+SI=,tag:K42SpNgV1k5ffx/cJJR5fA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:BnWPfL+KPLgVq/HqgpS2r4VNuww=,iv:+yFotIzaqK6140u5N6tHcFu/F4BVRcxXnt/fQiseQaA=,tag:M+Au9M4YKf8ozgJx65ZWrQ==,type:str]
    namespace: ENC[AES256_GCM,data:jLJBb7h+rkqUtkSy,iv:brrqkk845rJ+hAZaGKCQtofpHXqpA23G3Fy8uLuX3Us=,tag:jDlJAktrFwevDNWpdJg0Yg==,type:str]
stringData:
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:Jz3fE9FLFPxbU+SqvHIO282lkgRansNd4NnIOgw=,iv:yltxIIgB4kShvhYTUyWbK43qWY6VBFSQb9Z4qrpXxrc=,tag:9//9eXWn/XKCFGRosgD2Ig==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:Enl4GwZy7/9NFsHxiW8Tsok2HdZ/LshBMBefg3iATUqrJt1wCQ==,iv:lUYe9X0PFIUpnWW6i5a3UGGA0C1xxYRpzFr6eQqGGSk=,tag:prcrL3gmZEzmFPXpZ5TVJw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IElFSjZjRVhz
            a0ZpR2lUQXhBcTArVllqaHVKZGpobTNDbmE1UG1nL1RFdWh6MGpuZVRnV3FqNTI0
            NWVnekZTaVJxV2xpTzBIdGlvTjhORFUyTXRNL1orYjNkck1DRFl5L3hPZkZQVUNB
            eGowR0dONTArVi9GRm9ZZ2U5Znd1N3FWeW40K0NPWm9lTElWakxXTG1jU25LSXV3
            dTIzRFBFWGRSa1NyUWdjV3ZKTTVUa0s4VmpSdEJTWkpZMkVURldOaGUwSzVyeSt0
            Sjl4bWlsdE5FbDBVczlPcHdZVEFNTjQxY3hQamJvS2E1T3YybzdmWENscmc2UkdE
            QkJZM28zVWRhWGtQczU0S24vTnRsZGU1aEYyUCtIelZqTmFtODNLMjhHTVFqY09W
            QXU4ekNsUmNlMTU3SHk1citxTktHYXBFTW1veUxLMDJyUmppWnNMT0ZHZnRiTUhF
            RDh1YWhsSkVEOXhWM3FwdnJRYXUrVFF5ZHFUaHlDT3d0OXFHeXhvdEFzQmNhOXJr
            dFpHM2NuS3NMN01EMEtkR1NxR1hnckxNL0VoVm0reGEzOG9JdTloRy9sZHJVU3RI
            MkNRdlUwVENaaG82VHdPRW5FZVRPM1o2VkdMUHVJN1NLY3VLcVljMVpqdm1XdDVk
            d0VQL1BiWjZLYk1qRHBHUTczMTAxVEd5b0FOK25FNU81dnZGVE1XTkkwWUx6bU8r
            V3pxMkl6TFNWb3BCZlEzVkN5U1NvWGI2UXE2bm5CZGMrWGoxdU94UURaMG5QSEVy
            WGVLUStsSUtzdG15dkFJWG9IYXhZc3AzVGQyMjJIZFd4TmQ3ZmRnbEdjK2NWNU5K
            QjFDbEZ0YWp2MDF1YTdWWVZMTTFCc084dC9GQkgvcFlrNVRrZVYwMHl4UU1YYVdU
            M2dFeVJ6THg2YUxoVm9lTjZCaXR0M04vS1RsMzA3bCtsU01UckI2NFRmckpHN0wr
            V0VZV0g3Ymp0QzVyQXBnSGYwOU9yTkJQVzRESmp2eE54YkIwcnFhWXN1NEVucDRs
            RTNtd3hUeXlpQktsV1lSMURyREg0NGhSTTllTkU0VjZUSlJuOXRxaTRwRVFua0Z4
            QkVlcGN6YndpYUFMSFEwUytmT1NqUmJTbzV2Tjg1YnYzS2J5alNqZ1lpY2dydEFw
            dmp4TFBoK011UUFyMzY2OGZjQldmL2ZiSHB3R2ZubWNETm9HdzFKclMyTjdmcUNB
            NmNvcjJnVmVSNExxV0tvQ040KzIyL0Q3Mis0RU5YSDFWM2tNZTdhOG55SWREdTkr
            aGdMVGR3S1QwWmV3NDNrb1NUK1hwK3RkWUZBKzF0Ui9qVFEvN1NpSXdiWktTSUxx
            QU56OXZvbFFjZHNhQVlUck9DWlRodG5ML3ZMNXhmcGVoVkxYVy9USnRyUDl0SFlG
            VUFwVGpYcmU5V2lwcWY2ckdwYUIwRlF0ay9tbE1WVVM3cmZwRWMrWnlPVnpGV1g5
            cEx1eCtYZkh6am5sNERsNDhUeVY3TnRQVU5QMGdENDZ3RFFQZ25oa3lsVjRXZEFM
            UTJZUWRieFpQQUsyenNmS0EzRkplWVdDWHpueC8rTmxnZTZrdjVSVStDRXRRMHJE
            ejQyenh4Z1Fyb05SU2I3RUlDZk53WVpldjkyaGc1cjVQQzRMV2c1MkxEcmRibnlI
            c1NHZ2dhVVVJczN0aXlPcWpsWmk2TG1rLzA5OWZLVVQ3b2NNVGRXVWFySUhXeFJu
            dTRqOThES0I1TEtkZEZTYVlQWXhacUdTZ1V1bVFPQTF3S1V0Zk5kYUdDd203dzNn
            akp0REFQSXh1TmdaMk1uMGpPcFFaRlVBcnFSVlZ4dG9jbTJiWnRsVXZDNUlHZUZ4
            QllzajNuSHo4TDNBVDFqSDh0dGxHdEpVVzJkdXloR1R2aDE5NGVianIrd0lQakJn
            N1JHSFNLYVY2WjVhcDh3b1BoOHdhYytGZjZDZ09XT1ViSE1PaEhBWHA0bUZhdwpO
            enZUZUVhUWNScExwQ3NKa21ZZ0cwUGdxMno3bWhtQUt1TDlFTUVrK2RjCi0tLSBw
            ODJOaTJWWHVUVVdnckFhQkgydlZ4ZEJNT1VFb3puaE9xOGZ6WHlJaDVFCk+V4ps6
            deZCVD4fz1OCLlBS2ebV/NFdbwGcaz14MaOyDnovtUoOki/8b5bT9vvaPZL8U2y5
            XAayn4ZHL2gYaNA=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq182j3ewjp0rg2gfsanp9elcshzg9h5jpsqdxz24245fzz5fd366uksqvrq995x6kl0v53nevq4atfyhq53q98kl3sq4zf6uxpmh4sguvxwdg0p8dg6c6e45tjhymv63gnfltffzhsuf8gjhpp3l2caj75pgj7q8vtva25ejqckse8dxcmtxzryglf9dyqzst5mtcqaaenrhewk3rnp0z62kqrycrgyawgxn57t88mxxlpwv3tukryf9eh32vngzyeuzcvsa4za6kzf89qwxv3knmqhj9uzh9ds8n94yv8257q3dvluql30uy5ltgswgez5pxmkg6l2p53e7mn6xesy3ry48dez2ft2c23ewxde03mexfmc0mlsxu4q2n0qwxyreetz7npvjppzgmspqzlwf9gq7t3fcsu487xf06mas65kw9gru2skchuv9wcwzf89zhd52z8d44xu7sefxap2hqyyak8judkyzumvg2psxyvzmy8gkfz2qrz385xxljzwuut9vwwz2d6pd5044trh028fpqzcd8uuqwyv4gj8hv6vx3ktysgxw4tv9a83kae8mnqdcyvygfrtjedwrxgufv82ae5e8ru8txnxsmzadqaqy4yddpg7pjvw6gm437drvn9adv5mjnqx7wvjqj4tsmu0t99wwymel7g72qyvphygstan39f63z97azshhnreqdjrwc5j42e2xdwjyncq7vt9pe0y9qu43ywjacrw26zkfdvfnfvgmsxj967g6gd4xppem5m39smxzerkke8xcg4dzgxxgfg9f5peq0n6euzf6zsxj532k2cvlzc8q6m0t9x8gs8ll5gpvcnsmuq56stv5gru7d59uc3wpwfkespv3nec76jnyn7e79gzuevy96u2c2g7kg357ecv8qjge2sc6ragj9pq9yctev34djm5v02e2twkra7vs3rm6d7c2m6lcdkdm4pknkykc9quxtjrn9y5r42vg89jz49x3ga052wf2m6wglr5g7w53nzetzjudjx8ldxjgqp5c0yt9zfmx2zu76fkggn3rcugv035a0tzdyh79md77dh6kgqf9l5qrcrgk9cv9p9qks55ep8r9pcqnpmxcfy7ypr27zsh7upqle2kra6mv9aast4fe390sv3cv2hjdh3u4zf7upgqxg2wm9r0kswzhyt6rzjk33326vyk4amx92kzydnf9ccv0q6pcxg3nnp58tucw08fz6ym2d0ncvute9kgup7npd38x748egwdcv8czugdggg26uvl352w4znjcyze5u42xy8vc0fcajv0guhzq2vadfhcp4s0sz20dzntfw0hn6e4wm8h5ur5rq53g83ygxw4qez7amnnzf93skxmpdrc43v4en3au6z59y9xpsm9z3azv5thaxgph2fxewyx9d37r956g2nr5jn3msfqv4ssm2s39a3vcgd8sevl6deqysmhja5y2d5y0z7t0ak5xyfy4q557fxz2kgmgkq5mu60ya6eydfwzpf29vfklyll2f2de2hy2f79jx6xjwqt4fdxymyp2mcg7tw907hs2snfywfgagz5llfn4jd5pn74z6wtpgfqum4rssmpu2kqgtzyc3d4gcpqwdjsnwjzp4w2l5v9wnc6k5aw4q9z4wyencjtx3edwunfqn4tu9s2pqt8wl84y37qv5waukv78af0ywyz2redpmpkwzxu647gax95muz2s4fnydvtgh42vrlqqgulmt422zrjpmqvmxev5n7mku2tsmc599y2ym0sjwpacs8uztpzjyurgws390s2jxjzujw54usettx5uvf3q7wpqjkm55eqexddql87krt9wv2mnak5capzhk3lvs5ptafe9hex7v0znk76ma8yccuskv6y3stzzj2mh46w0cjmmuzf4yr96ecwtggvushzcltm3ss
    lastmodified: "2026-09-02T18:51:21Z"
    mac: ENC[AES256_GCM,data:KWeZVFUXF6jbcZTUSXoGuvJf5r2q9aZykrk4UbD5Nd3z7OTO+37Vy93hAWtRIYTn20N5u8U7qE13tChoh6uRbGPa49nltohRUZqRuCjC/SCzQDC0gf6aKzFxxUaegr6tTR96BpxNTo0SpEM+y1kAvcj8HP5Yph+lXW4OCAIjdSk=,iv:c3yK/hVo/8hYsx0UqoWrBWTD+7qF4VmWBfC8030W2ho=,tag:AXg5mYAlVZyXQGqKI3bCdQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
