adguard.opnsense.internal {
    @private {
        not client_ip 192.168.0.0/16
    }
    handle @private {
        abort
    }

    handle /oauth2/* {
        reverse_proxy http://192.168.30.204:4180
    }

    @unauth {
        not header_regexp Cookie "_oauth2_proxy_adguard="
    }
    handle @unauth {
        redir https://adguard.opnsense.internal/oauth2/sign_in?rd={scheme}://{host}{uri} 302
    }

    handle {
        forward_auth http://192.168.30.204:4180 {
            uri /oauth2/auth
            copy_headers Remote-User Remote-Groups Remote-Name Remote-Email
        }
        reverse_proxy localhost:3000
    }
}
