kanidm.opnsense.internal {
    @private {
        not client_ip 192.168.0.0/16
    }
    handle @private {
        abort
    }
    tls {
        issuer acme {
            dir https://192.168.10.37:8443/acme/acme/directory
            trusted_roots /usr/local/share/certs/tinyca-root.crt
        }
    }
    handle {
        reverse_proxy https://192.168.30.201:8443 {
            transport http {
                tls_insecure_skip_verify
                tls_server_name kanidm.opnsense.internal
            }
        }
    }
}
