- name: Initialize empty list for devices
  set_fact:
    storage_devices: []
  no_log: true

- name: Get SATA Interface devices
  set_fact:
    storage_devices: "{{ storage_devices + [item.key] }}"
  no_log: true
  with_dict: "{{ ansible_devices }}"
  when: "item.value.host.startswith('SATA controller:')"

- name: Show all values for selected devices
  debug: msg="{{ ansible_devices[item] }}"
  loop: "{{ storage_devices }}"

- name: Show devices names
  debug: var=storage_devices

- name: Show first SATA or NVMe device in the list
  debug: var=storage_devices[0]
