apiVersion: ENC[AES256_GCM,data:MYo=,iv:e1n/komiWTezaGEPNDmGmOGZROo33jHsUFB1X9gOXWc=,tag:tjlGruKI8Pk/omR7UAHXFA==,type:str]
kind: ENC[AES256_GCM,data:v7o4nOEn,iv:YkKC2nJlvee0Ws6XWas4cp0tvfq4LPd9NK0Hg1xa4Fg=,tag:Jgp2LRSUORseeQIRoPZxnA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ESCIwvfljH7AOc4rJRYNXocX,iv:bYVFXZMWzE3I0y+ko0kMO+h22Wu0Onl3Mt6BrLL+I5U=,tag:wi18vWtmh82Erf4J/df3Qg==,type:str]
    namespace: ENC[AES256_GCM,data:bNVWXEd8,iv:dOibtCaEm0x9yEOlwtepf3ehvDvUTnr8zp1M3fwQe+Y=,tag:jP2Aexs46LMqd2O9tQmkPw==,type:str]
    labels:
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:AC01nHmL,iv:L4YW8h2TGzXF7lvicp5SbQiuHOKlg3i8X6NN7+XXJe4=,tag:mgIwqFZ+Gxxaz0VBhFn+gA==,type:str]
type: ENC[AES256_GCM,data:r2M/VubV,iv:HvopnoZ3r1JSqCaJ0h0UGLGvgAKWDihfelbW4MyK0mE=,tag:tXPuVihZ4U5yO1eoQiAfuQ==,type:str]
stringData:
    clientSecret: ENC[AES256_GCM,data:LY8IQDNMIc69zs79FLrMqKwsPsQEnrq/psUiIyl00YL7a7/SXgURFyrrye8ha36d,iv:Xce+3k8SMnUo3XQnK6b2uugyUwYvf2M1AMcCPysR30M=,tag:szIH5U9EDfTbq0xOjZql0g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGVDSVJKNmg1
            bWpuUkdTZHRxM0hnREp4ekw5Z3RFS3VyRjN6b0JoSUdlWXZtT1RJd3llcFlLOXAr
            cTZYTkQ3ODgyZ0FUY3graExEbG5PYXRQbGlQSHZEdkdMMWpTeTJNZWIrUEZxYXFE
            MWNFNFNtT2RFb0w2Tlh4MmxZY0VmMVlGSUZkQlc1QkdvKzBWSk15b216TCsxZFdB
            L0xPTTdBYXNjVzN1N0YyM3hCdnJBRXpDdXpKNEVIU3BaUjhrZ0dwSmdCS1pSNDQx
            cms1VnUxSGdWRExjOWVJcGs0R2llWmRSalA2WlRLTXFoTkFrY2dYT0pKNTVXTE1E
            Y1JidDI4Q0FZS255MTVmMzRialZTU1dyK3U4R0o3SjRKOVVMWmszenJIMXhnRFJX
            Ym1kSXI1bzVObjNQaFBIS0pEMFNKM28zaVloNkh0bXF1SUtaTnBBZW9INnNIUHQy
            RGdjVGV5NGZGMWc3Z21OeGdPVmJXaU9IZ2JEMDJMR2dNbVVZa0hCRjhkcFkzSlR0
            aFNNRUxzYm5pUUxNclFKQ2NvRXErV25DV2N5am8xUXdENUdmYWJuejJrWlFHeVNC
            bXlRNS9naVUwcnpyVXFXV0dDRDhOZkJzaEluYkxONHllTjdYOG5DVVJDZjNmNzg2
            TEFkYjdUN3NKNUtyODg5ZEZQMnB2SnhHcXRmNExSSHBlR0JDQjhac0tCNkRuekM4
            dk5Dd3Z6bGFUNmZOZUVNRjNoTVlpWmx1YmZpRE1wekN5dWtGUk1jZzZRSXEvSW4r
            dUJpdDdUNXFJNU51OXFyTkZQZ3Nta014R1JQT3dNMkV3UXhEWEgwSkZSbG9UTnZV
            N1dCS0wrOFBrQVVJdUhnbjZjS1kzUkNTMTVhamR4SmtibG0zK1lKalhIZ1NzMEdH
            T0hyUDdlUXNCN0hwU1dHY1BOcVNQMlBZSjIxaDRWM1B4MXVGK0MyU3JqT29vdXNj
            cU02Y014NUZqejE0cHBYajZDbjVONTJXM0lwTjdEMGhwRDhhOVpPZ2s3L3hnN0J5
            bDRyYnNtSjVZOXFMZ3FiR25qelNxZXVOSjF2bGUrR01TTURNbmk0Uk1XWVQxRTJF
            WUZMbHhlakZ1UmR6V3V4aW0xc0FONTRMVkZtMnBsQm9LUElxT3lrL0hnMkE4NWFt
            Y2FPaHNtaDR0RDFKTWJ6ckpqZ3NwTnNxaW05THpHMnZpTm82ZzRlaHBmSWFDb1k4
            a0hEN2xjdllYV2RXUXJ1Z3RpeG15WDRHMUk2MnEzbE9KaUo3Sld3dEZhS0g2OHpI
            eG14ZFNySkNsVWpBUmFnd1cwSkF4SzU5QnhPZzQvbDZPYkxXN0NTZGk0Tm5KT0V4
            bmdTdGlQY3RsQ212VzViNlpFbWxLb0lWVkpDaDZzVXhaR0xFRGpkWXBhd3gvQlNS
            bGZLQTdKQ3RBYndOdXB3VUdnZzM4R25qZk41MDlVRHAwUGVBclE5U3laeGlDVkhR
            VTdBRUgvdzlLdURhdmEraTV3MGk3bUpGLzlGdC9QSklqNndyRE0vcmxHc3IycXRM
            T3E3dXk5T2N1aWRpQjBSMnlpVEV4TUppdXJBZnYzd2szQnZpaTBOYkw2c29admRE
            ZGFnUnJ1OGVVb2o4cUREb3RnYTlrSFlZMDN3U3psQ21waCtSVDFYNVVTUnNPeU51
            RkNSR3UzUStxdWRjeTRiTlNCNFNYTkp5NjRIV2tuV3hCM1ZZdHdMMTZSVEdJODl6
            alFNTTdwVFl5NCtXMU1ER2RaOEpGZmkwMUNldUFyTTVlUklGWUUyVkMzclNRVi85
            S1B1TDBjVjRkdjd3OHRKaVUrb0tQRk9WbkFxVWhzaEJaQzUrUEh5V3Y0WWtGdGts
            UW1SdW5NaWswUC9SNCthTXdqb3lWWVBZZDhkYmxIR3FUemdBY3diZ0wwTGF6L3cr
            ZUxMTzVJcElFSUpTdGdEdzBoaEtPaW5sYjNVRjdMZEZ2TDYwNjBOMTUxVWFNUQp3
            NTMyVDMvbXQ1TUVWWkN0dUdvNWNMVkJVTVQ2OUxGN0tSSmwzU3JYb2dRCi0tLSBo
            QmhvRkNQNzBEZGsxc05HbUdnQU1rRXpERHQ2MmM4ek1GckZDU2FLT3ZVChwSLDRl
            knWlqob+P6x6pl7T9V2Ep+4SFs6vOy90RJTiXmec10oCJOd64Th0UnBNP0mBj8Jt
            FYs+Th8aZ1VxYW0=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq182j3ewjp0rg2gfsanp9elcshzg9h5jpsqdxz24245fzz5fd366uksqvrq995x6kl0v53nevq4atfyhq53q98kl3sq4zf6uxpmh4sguvxwdg0p8dg6c6e45tjhymv63gnfltffzhsuf8gjhpp3l2caj75pgj7q8vtva25ejqckse8dxcmtxzryglf9dyqzst5mtcqaaenrhewk3rnp0z62kqrycrgyawgxn57t88mxxlpwv3tukryf9eh32vngzyeuzcvsa4za6kzf89qwxv3knmqhj9uzh9ds8n94yv8257q3dvluql30uy5ltgswgez5pxmkg6l2p53e7mn6xesy3ry48dez2ft2c23ewxde03mexfmc0mlsxu4q2n0qwxyreetz7npvjppzgmspqzlwf9gq7t3fcsu487xf06mas65kw9gru2skchuv9wcwzf89zhd52z8d44xu7sefxap2hqyyak8judkyzumvg2psxyvzmy8gkfz2qrz385xxljzwuut9vwwz2d6pd5044trh028fpqzcd8uuqwyv4gj8hv6vx3ktysgxw4tv9a83kae8mnqdcyvygfrtjedwrxgufv82ae5e8ru8txnxsmzadqaqy4yddpg7pjvw6gm437drvn9adv5mjnqx7wvjqj4tsmu0t99wwymel7g72qyvphygstan39f63z97azshhnreqdjrwc5j42e2xdwjyncq7vt9pe0y9qu43ywjacrw26zkfdvfnfvgmsxj967g6gd4xppem5m39smxzerkke8xcg4dzgxxgfg9f5peq0n6euzf6zsxj532k2cvlzc8q6m0t9x8gs8ll5gpvcnsmuq56stv5gru7d59uc3wpwfkespv3nec76jnyn7e79gzuevy96u2c2g7kg357ecv8qjge2sc6ragj9pq9yctev34djm5v02e2twkra7vs3rm6d7c2m6lcdkdm4pknkykc9quxtjrn9y5r42vg89jz49x3ga052wf2m6wglr5g7w53nzetzjudjx8ldxjgqp5c0yt9zfmx2zu76fkggn3rcugv035a0tzdyh79md77dh6kgqf9l5qrcrgk9cv9p9qks55ep8r9pcqnpmxcfy7ypr27zsh7upqle2kra6mv9aast4fe390sv3cv2hjdh3u4zf7upgqxg2wm9r0kswzhyt6rzjk33326vyk4amx92kzydnf9ccv0q6pcxg3nnp58tucw08fz6ym2d0ncvute9kgup7npd38x748egwdcv8czugdggg26uvl352w4znjcyze5u42xy8vc0fcajv0guhzq2vadfhcp4s0sz20dzntfw0hn6e4wm8h5ur5rq53g83ygxw4qez7amnnzf93skxmpdrc43v4en3au6z59y9xpsm9z3azv5thaxgph2fxewyx9d37r956g2nr5jn3msfqv4ssm2s39a3vcgd8sevl6deqysmhja5y2d5y0z7t0ak5xyfy4q557fxz2kgmgkq5mu60ya6eydfwzpf29vfklyll2f2de2hy2f79jx6xjwqt4fdxymyp2mcg7tw907hs2snfywfgagz5llfn4jd5pn74z6wtpgfqum4rssmpu2kqgtzyc3d4gcpqwdjsnwjzp4w2l5v9wnc6k5aw4q9z4wyencjtx3edwunfqn4tu9s2pqt8wl84y37qv5waukv78af0ywyz2redpmpkwzxu647gax95muz2s4fnydvtgh42vrlqqgulmt422zrjpmqvmxev5n7mku2tsmc599y2ym0sjwpacs8uztpzjyurgws390s2jxjzujw54usettx5uvf3q7wpqjkm55eqexddql87krt9wv2mnak5capzhk3lvs5ptafe9hex7v0znk76ma8yccuskv6y3stzzj2mh46w0cjmmuzf4yr96ecwtggvushzcltm3ss
    lastmodified: "2026-09-13T11:46:55Z"
    mac: ENC[AES256_GCM,data:CrYmYI+3VmIMBLKlWfOlzolL8CjXBd5W0uad3GHiOtavEYmA0LiwwqxT8Atw4DVQjzwwz1BGck3Rduzt4bQdNR0txScHVYxN7JUuT6fh3hUfTUTmHZh3q7AsadqE29e75SoFJ+hO56MiWrzTZf8iIL5iGw7Mk8U8G/4bnizTq6Y=,iv:boF+Ag4lsDKIaFKvDKLxJT28ChZ5Kg8hIvt35YdLsC8=,tag:dEnubkfA0A4OQDJZCUsU8w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
