---
clusterName: turingpi
talosVersion: v1.13.9
kubernetesVersion: v1.36.2
endpoint: https://192.168.30.99:6443
allowSchedulingOnControlPlanes: true
cniConfig:
  name: none
additionalApiServerCertSans:
  - 192.168.30.99
  - turingpi.homelab.internal
patches:
  - patches/all-nodes.yaml
controlPlane:
  patches:
    - patches/controlplane.yaml
nodes:
  - hostname: turingpi-1
    ipAddress: 192.168.30.103 # MAC Address: aa:b2:46:d5:be:e7
    controlPlane: true
    talosImageURL: factory.talos.dev/installer/2514fe5d294a5f96447ce4ea8ba0ff5cd2939607c4158c5806ade76bd1b076d7
    installDiskSelector:
      size: ">= 8GB"
      type: sd
    networkInterfaces:
      - deviceSelector:
          physical: true
        dhcp: true
        vip:
          ip: 192.168.30.99
    nodeLabels:
      node-role: standard
      topology.kubernetes.io/zone: slot-1

  - hostname: turingpi-3
    ipAddress: 192.168.30.104 # Mac Adress: 86:7c:01:bc:03:e2
    controlPlane: true
    talosImageURL: factory.talos.dev/installer/2514fe5d294a5f96447ce4ea8ba0ff5cd2939607c4158c5806ade76bd1b076d7
    installDiskSelector:
      size: ">= 8GB"
      type: sd
    networkInterfaces:
      - deviceSelector:
          physical: true
        dhcp: true
        vip:
          ip: 192.168.30.99
    nodeLabels:
      node-role: standard
      topology.kubernetes.io/zone: slot-3

  - hostname: turingpi-4
    ipAddress: 192.168.30.105 # Mac Adress: 16:98:62:87:6e:1b
    controlPlane: true
    talosImageURL: factory.talos.dev/installer/2514fe5d294a5f96447ce4ea8ba0ff5cd2939607c4158c5806ade76bd1b076d7
    installDiskSelector:
      size: ">= 8GB"
      type: sd
    networkInterfaces:
      - deviceSelector:
          physical: true
        dhcp: true
        vip:
          ip: 192.168.30.99
    nodeLabels:
      node-role: heavy
      topology.kubernetes.io/zone: slot-4
