---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: ext-authz-oauth2-proxy
  namespace: istio-ingress
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
  action: CUSTOM
  provider:
    name: oauth2-proxy
  rules:
    - to:
        - operation:
            hosts:
              - grafana.opnsense.internal
              - longhorn.opnsense.internal
              - zot.opnsense.internal
              - hubble.opnsense.internal
              - kiali.opnsense.internal
