apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-ingress
helmCharts:
  - name: gateway
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.29.2
    releaseName: istio-ingressgateway
    namespace: istio-ingress
    valuesFile: values.yaml
resources:
  - certificate.yaml
  - gateway.yaml
  - authorization-policy.yaml
