apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-caddy-local-ca
  namespace: argocd
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIBozCCAUmgAwIBAgIQb1dsuhrPlPg7uVhdzg8NMjAKBggqhkjOPQQDAjAwMS4w
    LAYDVQQDEyVDYWRkeSBMb2NhbCBBdXRob3JpdHkgLSAyMDI1IEVDQyBSb290MB4X
    DTI1MDkwNTE3NDM1OVoXDTM1MDcxNTE3NDM1OVowMDEuMCwGA1UEAxMlQ2FkZHkg
    TG9jYWwgQXV0aG9yaXR5IC0gMjAyNSBFQ0MgUm9vdDBZMBMGByqGSM49AgEGCCqG
    SM49AwEHA0IABA6MBz/jDHp5URfrh+h7sxFh/2WUL40N54HrI3IAMBomUYCR7gLR
    oyfkQxVGwEmq/f7Y0JRJVx7j2MiwHUqS5jijRTBDMA4GA1UdDwEB/wQEAwIBBjAS
    BgNVHRMBAf8ECDAGAQH/AgEBMB0GA1UdDgQWBBT+5fAZ0qM/D+wDxNcUYymm1TB0
    OTAKBggqhkjOPQQDAgNIADBFAiAsD4uFBlhUIzUPHbycpc5ScNllVJVG8JH84rSb
    hJtVpwIhAPCBAztDVx+XW3DqRv5FlnSseEOpazcT365ApgOR6qWW
    -----END CERTIFICATE-----
