apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: "v1.21.1"
    helm:
      valueFiles:
      - $values/infra/k8s/cert-manager/values.yaml
  - repoURL: https://github.com/zmynxx/homelab.git
    targetRevision: feat/talos
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
