apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium-lb-ipam
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/zMynxx/homelab.git
    targetRevision: main
    path: infra/k8s/cilium
    directory:
      include: "lb-ipam-pool.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
