apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dragonfly-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: ghcr.io/dragonflydb/dragonfly-operator
    chart: helm
    targetRevision: "v1.6.1"
    helm:
      valueFiles:
      - $values/infra/k8s/dragonfly/values.yaml
  - repoURL: https://github.com/zMynxx/homelab.git
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: dragonfly-operator-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
