apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kaniop
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/pando85/kaniop.git
    targetRevision: "v0.16.2"
    path: charts/kaniop
  destination:
    server: https://kubernetes.default.svc
    namespace: kaniop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
