apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-manifests
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/zmynxx/homelab.git
    targetRevision: feat/talos
    path: infra/k8s/longhorn
    directory:
      exclude: "{values.yaml,nvme-wipe.yaml}"
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
