apiVersion: v1
kind: Secret
metadata:
  name: spegel-oci-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: spegel-oci
  url: ghcr.io/spegel-org/helm-charts
  enableOCI: "true"
