apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spegel
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: ghcr.io/spegel-org/helm-charts
    chart: spegel
    targetRevision: "0.7.4"
    helm:
      valueFiles:
      - $values/infra/k8s/spegel/values.yaml
  - repoURL: https://github.com/zmynxx/homelab.git
    targetRevision: feat/talos
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: spegel
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
