---
apiVersion: kaniop.rs/v1beta1
kind: KanidmGroup
metadata:
  name: argocd-users
  namespace: kanidm
spec:
  kanidmRef:
    name: kanidm
  members:
    - lior

---
apiVersion: kaniop.rs/v1beta1
kind: KanidmGroup
metadata:
  name: grafana-users
  namespace: kanidm
spec:
  kanidmRef:
    name: kanidm
  members:
    - lior

---
apiVersion: kaniop.rs/v1beta1
kind: KanidmGroup
metadata:
  name: longhorn-users
  namespace: kanidm
spec:
  kanidmRef:
    name: kanidm
  members:
    - lior

---
apiVersion: kaniop.rs/v1beta1
kind: KanidmGroup
metadata:
  name: zot-users
  namespace: kanidm
spec:
  kanidmRef:
    name: kanidm
  members:
    - lior

---
apiVersion: kaniop.rs/v1beta1
kind: KanidmGroup
metadata:
  name: hubble-users
  namespace: kanidm
spec:
  kanidmRef:
    name: kanidm
  members:
    - lior

---
apiVersion: kaniop.rs/v1beta1
kind: KanidmGroup
metadata:
  name: kiali-users
  namespace: kanidm
spec:
  kanidmRef:
    name: kanidm
  members:
    - lior
