apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - certificate.yaml
  - destinationrule.yaml
  - kanidm-cr.yaml
  - virtualservice.yaml
  - groups.yaml
  - oauth2-clients.yaml
  - user-lior.yaml
