apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: &name cert-manager-istio-csr
    repo: https://charts.jetstack.io
    version: v0.17.0
    releaseName: *name
    namespace: cert-manager
    valuesFile: values.yaml
