apiVersion: ENC[AES256_GCM,data:/k8=,iv:tpApNi5PkA2Rpz/F2y+j7KRznwkSRftupK/ljq9QDNE=,tag:r9incIJ4uyPWZFizESlEfw==,type:str]
kind: ENC[AES256_GCM,data:0hy8SY5K,iv:WWE9mdW+iprRsK9Ab0Iy0ZlXS4ZphdCFtPzQ5a402ZU=,tag:/h9BBMkNe+H3IQXoDTBK8w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:HT0jkJp5zxcxBYOniFGM6ZSGBA0=,iv:Mg8lSxTm/D92zmESfcdqMpsn9woyaonsQFad+j8blH4=,tag:1HyvznI4Z3PZAnbAPrs3JQ==,type:str]
    namespace: ENC[AES256_GCM,data:y/zH1JHCpCgD,iv:zgbo4u7aanUfARGnzIE4VuZYqUdAqXUuWx5hw3jrEyo=,tag:Qp4Xp1t+dMxwRkR/2KwsHw==,type:str]
type: ENC[AES256_GCM,data:nivzymi/hnUf3fQOUtdYnQtxTw5WxPke,iv:/h/Uaqdg0vaMiudLikK5S9pakYhLLgUuRSF59o/BFu8=,tag:LOvaeTf3I/wIPR+eCad5DA==,type:str]
stringData:
    username: ENC[AES256_GCM,data:+Q+Ix+Tx+nU=,iv:qomq/KbKEPS5LrnkMaWBujF5Nc8chwbnPfsHfjHooHc=,tag:5XGHnpgRK1nnFDe6vXLwLw==,type:str]
    password: ENC[AES256_GCM,data:V5QAWVLrypQUczG5BAnhIEDgR4wNjfhDX2x2YeOSFgushXh+/cmxrpNASHk=,iv:BApf4pAshk4WZeNr0HoGnIM1HQZFcgomgkya+iVxxDU=,tag:j849imUIRYxADmhHO+MB9A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEphWFJNeWpC
            dUpHM01qTGh4VGdxWGhhTjlzU010aGRWM3FscTVGbEtXU2VBc2pBWFhQYnA4ZXU4
            TkFLOHFjMCtheDhRc2c4RFpnNGJVUk0wcE5md0l1Z3JyMFA1Q0k5Y2RvYms0THRp
            S1dpMmhMNk84dEc1RDFHdzRzdDVxYW12WEQyMGgydGYxTW5lbUl5V1gwbWNNV0g4
            and2TE1yNzB2MkVzbE9nYWNXdlZUZERVY1o1NWhod0NtaisyazkyUUgzM0t5WlJk
            RHhTTW1INHg4M3ovMXQvQ09DWFkzQlhXb3hUTU55VEUwZS9MbXFnYVU5anEyV1cw
            ZUtwaWw0aUhJWWNNcGZqM3ExSFZOS3krNUNBY0ZNZEZGU3duelBjcHZRMnFJWXhw
            MERrMWxyTDFvczNENE84TkpFc0pnSHpqbnF5NERrODNMeExLdjVQbi95VEgvOXBB
            SUxwazBxOG1zc1JYZGFKMXRIWHdaTk5vWkNWK2tyaFFmMTgxWUU2Q0d0RXI4bjhX
            Y0V4QnprTU9CT0NTNVVKdUorenZOZXJ5TmZLbE5xVkluN3NzUGZ3UlIybmw0bTgz
            SVV3d3Yvd3haYUtTQjRqSmlqTTFueWFPcHRBUGJ3WGRhUURoYndWOEtNWnNocnNv
            WGhyVTROek9wKzF4Nm5pZHp5RjBDVklnVTNjTnVuRm0wTEt6Y0w4SEpyc3A3dnFP
            MEZXOVRIL1RNbjd5MktXRm1hSXRrL0hOaUV3aDRLRFJhNHhpRTMyeThWdzA1Mjdo
            dXErZExPMVI4Z1dlMjN4UXptOXdKV0N2RXFmZWRkT21WY3ViYjBmMGc4OURucHoy
            SmQyRkwzQVRHa0RoUWtZaDVaVmlmd0R5K09xM2hobDFlK0J5Z0R0emRUS1J0YTht
            WVN1YjBIa3pSeFFnK0xUbk1yaWVkNldkRWloKzd3T3NxRjRtRkQzWHFpYXlTZjhq
            a2lvYTEyLzVEeUtsVU9vekMrWTR6OXNDbmdWaHNjVm9TeDZsdEE4RjdXdGpOQlpR
            WW54WDNmeXU2WWdJd3E1S2FCSGl5VkNZTmNXeHFzSC8wWkdpZ1daTTVCWDE4aE9o
            ZmFGZVpNTnF0ZzZBSW44OHpQQkpJNVh4em85QU1nOFZadmYrYjZ4S2ZFaWFFbzFM
            UmFiRWJVRXNPY2s4aXQyaTFZNkl1clJpK3oydFBoUFQzamRZN0p4SHM1b1BTZmJC
            NjFUZGwvL2JXMHkwaGgvMUNJSUl1UU9TYXBWemVCYmNOYnJQcjB0TjB0MjJmRERm
            Z25sa2JkZHVOc1RVZkpMVU1GSEVYdk1GVk03bmRYVHR3UlhoZFVIQXlpOThTeXdH
            ZzV2b1dDTnNTRGFoeHd0NjUwd3lHWElNcDlXRmZRMUFKbEFHdGJaMnJNZldmbUs5
            Tmd0TEVsL1EwZXlUR0wxM3hNb0s4K0MvNXFQYzZvVVNjTDJlVUgzTDAzOUhKYWIz
            bysrRi9YQ2JseXNxUDI0eExSbXBoNlhhTHNmT3QxRGplTm9VNS95dEU4WUJPZDRX
            Rkw3R0NLdnFPWXpwbWp6Q1hFK2dnRFVXQ0RqdmJ1NFFFMFFZbFlvcEZCYTM3Wklj
            Wk9jeHh6RXpFaHlIUW5sb3Q5SHhiODFsR29WY0JRNWdaUm5vRjZzZEFkYmtMOUg5
            eEFaMnpQZ0srcFcrZHY1T0ZoVUJodjJ6bFdCcFJBWlRMd21ZcFZhd1hlZzVkSGNs
            d21icW9EWUVzcVozbVJVSDhxSjRnQnRHZmt5K2hCQ215a25Tc3Y0R3FHZkF5S2FV
            L05NcVUxWk10TFlMaUdMVmh3WkRETVhwSHgydGZvZklRcTA1Z1U2UlJOOUtPcVA2
            YWNUSHRFaXY4elU5cXZYV245M0NGczkyL0JjY3k2K1RCTWFPUnFzNmxCcHB4cXk5
            QjE5aGFIdWk4V0k4VnVubFI5RGV0SVV3cUpXaFBSSEw2YSs3eVhRY1E2VFBOZwp2
            L3ZWakxxbUV6bkZoN2tnWktaL1VGYjN1UEREbDkrQmc5RkR5M2crNVpnCi0tLSBh
            QlA3OSt4bWZKdkJrU3pyU0x5M3laQktPNVBTa3QxdUtxVnM5a05UWUJ3Cu9C8L3s
            c/H/sSB6Pl073YMgzMxscLdoL369hGvJyenYSimA4ZR6LAUydHr74cI7gzu80T6f
            HFXCImGIm4rOxQg=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq182j3ewjp0rg2gfsanp9elcshzg9h5jpsqdxz24245fzz5fd366uksqvrq995x6kl0v53nevq4atfyhq53q98kl3sq4zf6uxpmh4sguvxwdg0p8dg6c6e45tjhymv63gnfltffzhsuf8gjhpp3l2caj75pgj7q8vtva25ejqckse8dxcmtxzryglf9dyqzst5mtcqaaenrhewk3rnp0z62kqrycrgyawgxn57t88mxxlpwv3tukryf9eh32vngzyeuzcvsa4za6kzf89qwxv3knmqhj9uzh9ds8n94yv8257q3dvluql30uy5ltgswgez5pxmkg6l2p53e7mn6xesy3ry48dez2ft2c23ewxde03mexfmc0mlsxu4q2n0qwxyreetz7npvjppzgmspqzlwf9gq7t3fcsu487xf06mas65kw9gru2skchuv9wcwzf89zhd52z8d44xu7sefxap2hqyyak8judkyzumvg2psxyvzmy8gkfz2qrz385xxljzwuut9vwwz2d6pd5044trh028fpqzcd8uuqwyv4gj8hv6vx3ktysgxw4tv9a83kae8mnqdcyvygfrtjedwrxgufv82ae5e8ru8txnxsmzadqaqy4yddpg7pjvw6gm437drvn9adv5mjnqx7wvjqj4tsmu0t99wwymel7g72qyvphygstan39f63z97azshhnreqdjrwc5j42e2xdwjyncq7vt9pe0y9qu43ywjacrw26zkfdvfnfvgmsxj967g6gd4xppem5m39smxzerkke8xcg4dzgxxgfg9f5peq0n6euzf6zsxj532k2cvlzc8q6m0t9x8gs8ll5gpvcnsmuq56stv5gru7d59uc3wpwfkespv3nec76jnyn7e79gzuevy96u2c2g7kg357ecv8qjge2sc6ragj9pq9yctev34djm5v02e2twkra7vs3rm6d7c2m6lcdkdm4pknkykc9quxtjrn9y5r42vg89jz49x3ga052wf2m6wglr5g7w53nzetzjudjx8ldxjgqp5c0yt9zfmx2zu76fkggn3rcugv035a0tzdyh79md77dh6kgqf9l5qrcrgk9cv9p9qks55ep8r9pcqnpmxcfy7ypr27zsh7upqle2kra6mv9aast4fe390sv3cv2hjdh3u4zf7upgqxg2wm9r0kswzhyt6rzjk33326vyk4amx92kzydnf9ccv0q6pcxg3nnp58tucw08fz6ym2d0ncvute9kgup7npd38x748egwdcv8czugdggg26uvl352w4znjcyze5u42xy8vc0fcajv0guhzq2vadfhcp4s0sz20dzntfw0hn6e4wm8h5ur5rq53g83ygxw4qez7amnnzf93skxmpdrc43v4en3au6z59y9xpsm9z3azv5thaxgph2fxewyx9d37r956g2nr5jn3msfqv4ssm2s39a3vcgd8sevl6deqysmhja5y2d5y0z7t0ak5xyfy4q557fxz2kgmgkq5mu60ya6eydfwzpf29vfklyll2f2de2hy2f79jx6xjwqt4fdxymyp2mcg7tw907hs2snfywfgagz5llfn4jd5pn74z6wtpgfqum4rssmpu2kqgtzyc3d4gcpqwdjsnwjzp4w2l5v9wnc6k5aw4q9z4wyencjtx3edwunfqn4tu9s2pqt8wl84y37qv5waukv78af0ywyz2redpmpkwzxu647gax95muz2s4fnydvtgh42vrlqqgulmt422zrjpmqvmxev5n7mku2tsmc599y2ym0sjwpacs8uztpzjyurgws390s2jxjzujw54usettx5uvf3q7wpqjkm55eqexddql87krt9wv2mnak5capzhk3lvs5ptafe9hex7v0znk76ma8yccuskv6y3stzzj2mh46w0cjmmuzf4yr96ecwtggvushzcltm3ss
    lastmodified: "2026-09-02T16:18:42Z"
    mac: ENC[AES256_GCM,data:7BjyjvoM0EtKbmpziQsT45r+8BQDYhYw6g8SMxQ0mAMJ6yXt88S1kAhXMSYM5E+Qz3NFVxTkn0D1xjxh6Lfem3M8rQZeiX7g1Vs0J6g91RUyoNLI2dUnO5oPFNqB6YDjJBl73PYv7GQyr1LNUSDkwkSWk1VHp9lYEMaNCSq7XMQ=,iv:tGoIvjPvOZtskrp59PEx0dAt/AEaF0qKwDDCcmygbTA=,tag:8B+BKZhpcaWbzlc0y60kGQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
