apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: &name victoria-logs-single
    repo: https://victoriametrics.github.io/helm-charts/
    version: 0.13.9
    releaseName: *name
    namespace: monitoring
    valuesFile: values.yaml
