#ENC[AES256_GCM,data:MSscgAxRvYc763v+8d8D+CLEZsZ0X4p9Sl/Gfoj2KyDRzXauepfPrftqIZeRS90hnotKmWW66x5ESXCA+9HncWA=,iv:RQWnuiPGpvgXAS3k7ZFGIqU98DS7oBuzMa9+00PvkA4=,tag:F77zzvRcCkyp+VFMRSzOaw==,type:comment]
opnsense:
    api_key: ENC[AES256_GCM,data:LPj/8QNVQLzcGGrzZ6ZI6VsIPaS+Fn4zhtg0ejpdne08GgjY+5e0LuYYr2Ty9v+mlyeO2E7vaMotlPft6dOtft4CikB8jp8HY3TWY8mHn2E=,iv:yBsO7AF3myhjyPlOBvplXFpUVEDFiJQ2hYV+/QHRcg8=,tag:qvs0BcFcEoKfqgW//PlBpg==,type:str]
    api_secret: ENC[AES256_GCM,data:DuQYbaIQQmeIyjQzwkTArR00/jKvEiVVukDiqBPiNeC1bLiunmZVpo3hm+STv7rB93I0eJ2/3ogaT3jo0xv3rOAeeV6CtIKEbAr/2+xDSWQ=,iv:PvWIHpadid3d+GybQgliu2FKF+DYjx/d7qO1F0nIXjc=,tag:c1Mef3xzk28rN+n2okC8qw==,type:str]
kanidm:
    admin_password: ENC[AES256_GCM,data:QNW0YgONKrhSxHkiV14pjryuTO5JDO49XRtN13WSlG+iMvsm270oK0G0V2HdKCgM,iv:HQyGsm1hbvZzRIP7G/2vtX0fbH/x4Do4RU+izdDBQ/g=,tag:o/grGtz+pPHhngV91EAZ9w==,type:str]
    idm_admin_password: ENC[AES256_GCM,data:MMfy7UgYcd+BjiGHdufNwQ9T2m4x7QxmG5UAuWSC/nUpqL+YyqT2V1MO7Y3l8PWR,iv:sEB6u3/KurNeq9qzb27Lp1MHLQMTDLHJ/9wlPsXb9nA=,tag:FBHw4K4FfVcIv3J9ysgQsg==,type:str]
oauth2_proxy:
    client_secret: ENC[AES256_GCM,data:SK7B5E+TqzS1DC3v7qQOPBNtn3AdK1yXjojuDGbjWNExuYdd+XpfzyDEW79QDnx/,iv:JQzOn+IFjNXALLcZT+Mvnvm0gPuDawb+rqp5MRHaTt0=,tag:SD55xNmyeAgkDL/sFDotsw==,type:str]
    cookie_secret: ENC[AES256_GCM,data:9ucYu/EHs/ahh5GcORgf05sXql9S/sgED1Rn9IRPm5k=,iv:qyk8E2hDpgErml+eWbnYc1ZC5e6+MEUNYLOJ/I4nEdk=,tag:Z5ZzzSPullz+VIp6XmWO5Q==,type:str]
argocd:
    kanidm_client_secret: ENC[AES256_GCM,data:d6qGzLYDH0wSZxZGLwDyMu9cY1cnQC+tzniZ1w6wruQt+VYUvN9ogBzpjJXR6AWS,iv:DX+0NG1W0RQ0n2U4gPuCcuHzGJtwn17Iba8iRQIM+sc=,tag:LGoQAZNyi8oloXcQ7bI6yQ==,type:str]
#ENC[AES256_GCM,data:yma8bJZ2mxnOfA7zrFFUR9P3YFI4DmR+B2bk96vBiJig/Exz,iv:PYaBzvc3ikXtiUyK8u54MHkP/8JkNdSepcirwF3M49I=,tag:WF670xPhrabo/47wvXmT4A==,type:comment]
adguard_oauth2_client_secret: ENC[AES256_GCM,data:WCPoxUKWTB9mhKaE6IdmWlQ8ZXZXnRudgsauqK7/0aFVBJPS7J51EGTHPG4+oA7s,iv:uEWdO9u2K79288rAVfK052V7F/vQcjSRn9hF9aAuKdA=,tag:ba8nmZZOsjkESPmt27HACQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEZ6K2l3RGRt
            WXlpZzhHbkZ1NkUyWjh1VW1uYWp4VmJyeHZQaWtRU1FuNmFQL21sN3NiMURoMmxw
            L01Jbm9sVTdSQVVpai9hR1Q3dXk5TVZaOThmRWFLQWV2dmU4ZmNBcVRvRTVZQ0Rz
            WFRGOFhiM0p2T2RzTVF4N3JTeEhOdjkwK1pIY3Bra1hRd2tMWTQwS3dYMktkbGts
            MGhBTUVYVzdCZmFrSWVMQWpYaUlRS05VTjVFUDA5eVVudC9HMzFBMUxBRkpDTVcx
            eHVSZHdjQXB1WkpaakpkbXRKWHpDa2gzRVc4WGJLd0VMUmxzTkRMNzVUZXhDZUtn
            Tkhic0pwSElRSGFoSnJmckpZb0hobmNKOHRyMzhZWW1ndkZrd0h6MDlRdWZ4VXE4
            OEFtcE40TUVKYzhRVHVOdFpWVzZvMUNLLzlZeVVpdWlGdXJLL2VKTHFkancyeU5p
            N0JxYzRFeGVnY2NvZDBvLytZTnkxMFh6Wm1FSlVPbG1QWGcycXc3azlibU1Xby9h
            VjEyeHZvNUVlaUtVcnhpMVo1Z1N0cVU4Ukl2dHlOVnVFWktTLzZlWU4zNGNpUFR6
            eUo0Q1hCVDlaMFMyMEJFd0hlRU1pWHQ5My8xUk9MYmx0UEpmc2FobnczMVhrUDNr
            MUZBdTN3U25kY1FQK1Q4eVNLM2RiVFhFMXlBckliSHNSNVdWRUNrOGFVb2IvbU56
            Vy9TOVBDTlgrWjQraXpYb3NYVDVkcjZsa2tZcjRGZFVudzVrL0sxazUrYURidVVr
            U3pBUlFYdzRmRFRtcjFDSHFjRTJXcmNJaFdXRDRIV0JHenhocmVQTVlSSE8ybWg1
            dUs4WFREc2diMzFnOW00NlF5andRVzQyTHdUWWhPR050MExkNkJQVkptSE9Oa3Vr
            UjB5OGt1clVvZjdWY1h0b0tqc2pHb0xjNUFqU2VNaE5LbnhvS2I0aTl1alE1Zzdq
            OS9WYi8vbS8zNkVnY3BiRjV4L3NVK1FJRDNsSGs0anZUQmVSZ1BORkFYc3I2TmIz
            R1dKVU9ZcWdNbms0UCs3R01ZWkVsaE9tNVhWRXBBeHozL3ZtaERsdGZIc3VabEZn
            WFZwaldhdDdCOVpZeEhSZFRodjRDbDE4dDZpZmp2YXV4L1BLVXk0Y2RCSllTdHpm
            eVUxcXhRaTdUaWJ1anQxT2dsMlkzZklma01peWViZVF5TmNOc3FqOUVsNTRxMGVM
            ODZKSWxoeCt5RzlLKzV3dXNPQkhQamQ0THNPNzhUZ3dhYmx6TEMyTFM5bzNrUHhw
            dXV6Sy82N0UwRTl6RHp0VkVXQVpwT3JSU0dPVVNaNHRuMUZJekViWHEvZGFGWXVM
            aWIzSk5CNkVKTXZ0UW1zQUxWZytmQTh1MVkvQUgzV3JXem55VnhQOGE2c2VQa21G
            Y0lkR05nZmdvdUJyWFZmc2JUNm9HLzVMRHVFQmJTNldPVDJ3VjZtaHJmTUR0TXk1
            Nk9KWFdNMjhHQlVXUlRNUmZaMnc5NmV1aEdCVU03RU4rVmZ1QU96dy93WEw1T1I2
            YWRVbnd3aTdvb21rdHBrNEcwbGRqbkM0N0lydnNzYllXNnYyTVlBYkpyVXpYMFhk
            TFJreXZYSDY2VFBDdEwyN1puT0NFaDNkaHpnbXRNQ3czeXBsZDVTVXhOSHhyRURu
            eHRrRVJHb2xrZ2hOaG1WRk9TVVQrUTRlNTVpNUdMNjZoTHR6eG1LREszUThmcEtM
            eHRua1YrZXdNMXN0NDdWMFlSYU82MXpVSlZwVGphYVdTbm9mTUhyL1dDV09CSW1P
            aUg2YjNxRllEaGJLaGpyNzU4Ui9aL0ppTWU1dGkzNUN0ZDdOZkdSdUtzK2VDb1BY
            Tm45MmUwRTdTVGtIZ1RDR3FTUHN6d0RwNzJDWlA2eVJRMXVIUDJaZHpPRjJBUkhm
            NjVhTnVVdUx2clpnZ2JPMnFaREs1Vjg4ZmFPcHFwNWtDbFN5U2lGa3htdFRFUQpG
            QkxXaitvVGxxcnN0WDVzMW9oc3ZvdnAwdjJEL0tNRVJYZEV5WmtiTG5nCi0tLSBT
            NDZGZUMzM0sra1cwckxGQ1I1SjI5NFNUM3hWRlZOS2t3MzRyUTAwR01VCsDf+RX5
            Ln/0+xb49eY5tUfzR+B+vfpHkHudbYTDkS5dbKSlGxtlcviRpbtEzI8TysoSMM7q
            hcDfA4fRfW/LzcQ=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq182j3ewjp0rg2gfsanp9elcshzg9h5jpsqdxz24245fzz5fd366uksqvrq995x6kl0v53nevq4atfyhq53q98kl3sq4zf6uxpmh4sguvxwdg0p8dg6c6e45tjhymv63gnfltffzhsuf8gjhpp3l2caj75pgj7q8vtva25ejqckse8dxcmtxzryglf9dyqzst5mtcqaaenrhewk3rnp0z62kqrycrgyawgxn57t88mxxlpwv3tukryf9eh32vngzyeuzcvsa4za6kzf89qwxv3knmqhj9uzh9ds8n94yv8257q3dvluql30uy5ltgswgez5pxmkg6l2p53e7mn6xesy3ry48dez2ft2c23ewxde03mexfmc0mlsxu4q2n0qwxyreetz7npvjppzgmspqzlwf9gq7t3fcsu487xf06mas65kw9gru2skchuv9wcwzf89zhd52z8d44xu7sefxap2hqyyak8judkyzumvg2psxyvzmy8gkfz2qrz385xxljzwuut9vwwz2d6pd5044trh028fpqzcd8uuqwyv4gj8hv6vx3ktysgxw4tv9a83kae8mnqdcyvygfrtjedwrxgufv82ae5e8ru8txnxsmzadqaqy4yddpg7pjvw6gm437drvn9adv5mjnqx7wvjqj4tsmu0t99wwymel7g72qyvphygstan39f63z97azshhnreqdjrwc5j42e2xdwjyncq7vt9pe0y9qu43ywjacrw26zkfdvfnfvgmsxj967g6gd4xppem5m39smxzerkke8xcg4dzgxxgfg9f5peq0n6euzf6zsxj532k2cvlzc8q6m0t9x8gs8ll5gpvcnsmuq56stv5gru7d59uc3wpwfkespv3nec76jnyn7e79gzuevy96u2c2g7kg357ecv8qjge2sc6ragj9pq9yctev34djm5v02e2twkra7vs3rm6d7c2m6lcdkdm4pknkykc9quxtjrn9y5r42vg89jz49x3ga052wf2m6wglr5g7w53nzetzjudjx8ldxjgqp5c0yt9zfmx2zu76fkggn3rcugv035a0tzdyh79md77dh6kgqf9l5qrcrgk9cv9p9qks55ep8r9pcqnpmxcfy7ypr27zsh7upqle2kra6mv9aast4fe390sv3cv2hjdh3u4zf7upgqxg2wm9r0kswzhyt6rzjk33326vyk4amx92kzydnf9ccv0q6pcxg3nnp58tucw08fz6ym2d0ncvute9kgup7npd38x748egwdcv8czugdggg26uvl352w4znjcyze5u42xy8vc0fcajv0guhzq2vadfhcp4s0sz20dzntfw0hn6e4wm8h5ur5rq53g83ygxw4qez7amnnzf93skxmpdrc43v4en3au6z59y9xpsm9z3azv5thaxgph2fxewyx9d37r956g2nr5jn3msfqv4ssm2s39a3vcgd8sevl6deqysmhja5y2d5y0z7t0ak5xyfy4q557fxz2kgmgkq5mu60ya6eydfwzpf29vfklyll2f2de2hy2f79jx6xjwqt4fdxymyp2mcg7tw907hs2snfywfgagz5llfn4jd5pn74z6wtpgfqum4rssmpu2kqgtzyc3d4gcpqwdjsnwjzp4w2l5v9wnc6k5aw4q9z4wyencjtx3edwunfqn4tu9s2pqt8wl84y37qv5waukv78af0ywyz2redpmpkwzxu647gax95muz2s4fnydvtgh42vrlqqgulmt422zrjpmqvmxev5n7mku2tsmc599y2ym0sjwpacs8uztpzjyurgws390s2jxjzujw54usettx5uvf3q7wpqjkm55eqexddql87krt9wv2mnak5capzhk3lvs5ptafe9hex7v0znk76ma8yccuskv6y3stzzj2mh46w0cjmmuzf4yr96ecwtggvushzcltm3ss
    lastmodified: "2026-09-12T17:24:19Z"
    mac: ENC[AES256_GCM,data:4Wc/96+lVDDJKvtL58vUI3BqyhJ/RZQxuOJq2DNxXmlRC/Mohpal79+ht5wzqg4a3JOwHOJLyhEtzCwd0fBJSMDqT7eYI3LgnkV0Miisl0FdmOBCUEjqCZ8Ls+IT8Q6ds6uR6q+TaKZpzqNDPOme4Ih6ZtcO7c6KwzhiKt92cMs=,iv:AguAwZcZCQkLrB+imFnFnRI8nXZte5tgBez4xmO4H18=,tag:fxknfvJnCNle4k62d6oq6Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
