# OPNsense API credentials, Kanidm passwords, oauth2-proxy secrets
opnsense:
    api_key: ENC[AES256_GCM,data:Ev2qg6hlhQU/h/EfvqcR1slmnNdXCosuVGJhNuNf8i0ZFME24Tu8X2YZVuicraOW4zZm11Obze5Vl//Pq9iEWHlEeHgu2kGGvdh8xLoHiIQ=,iv:laUS+yX7N7Hj4K0c7J4MV74DKoem1sgmlV2QXU7GB3c=,tag:oyQufnFpGnMDL54Pu+PhBw==,type:str]
    api_secret: ENC[AES256_GCM,data:Sdmz7Amw5OSvw1MMhnCDPwIX9BXFxIfXDm5SAItvxzkMLBbb09c8bffLqHh8fpH3SmxpZNmMcYdyrRhkYlXhd9LEouF8puBJ7DphkbYCmho=,iv:iHMRINwT5M/x1hPke1fCqrwW6xmxZ1H153MAJttIl5A=,tag:5RV2M8rRVdFpf1IueP8qXQ==,type:str]
kanidm:
    admin_password: ENC[AES256_GCM,data:15raCCrc65u+5wteS/9ejp+tmexELDclUDk3sj7shgxNaP+w89rA9Ss/QDeGjTCd,iv:fbrgW75YOcE/Ng0a6GV/Rzbw7Y4qiuuACnxAciDD834=,tag:Ojn7s5uRP57sGiclFFRA0Q==,type:str]
    idm_admin_password: ENC[AES256_GCM,data:FgmVdcrxQVCmHEha5MMCwtH2zq+e4xbWt3IsPEuNx2gAdqMbm3cN9Fw53D/OcFmL,iv:XWsd9/02K0ftCFNPxKZ4JgdtkFGr3M9BjqZ4+dpKzZk=,tag:wXDn7PkBgnSCI8T39QEybQ==,type:str]
oauth2_proxy:
    client_secret: ENC[AES256_GCM,data:0dK3wryBeDnLvUZvjY0MPSws7975/LT0ETcoGEw33/41nvzUejtEEd6Q08rwE+7m,iv:9I+IgBqvp7kRyS01S6jDij0M8qjV0A27bieqp7gTTAs=,tag:V3Ywll1kerODgThJq7nmjA==,type:str]
    cookie_secret: ENC[AES256_GCM,data:KB0r8fkZMdTguL2jP7D0vpY+lvHwHlCKMW2BXuAaDW0=,iv:88bh4xF7qCMrpYQ6SzGwjPn+IBTm1z3+sVl5god3nxk=,tag:Wb7HQmGoaAQha0Eei7qaXA==,type:str]
argocd:
    kanidm_client_secret: ENC[AES256_GCM,data:n/F5rGRbPGokjSTUZNfezckALy14FCs8RqQmCFH8wkCCLHCe3i6D8tCaFFDxGyzT,iv:uCxtgb/BBaFDCoxzieUBfMFJLtUItw2k9daWzeAkn8I=,tag:w//nkNyYpgGuMPPsqQDk3Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDI3NlJDL3U5
            UUs3UENFUkp0bXNWeUhDVWpZcTR4Nk9PSjhFcHkyQ0ZWN0Q0cHN0WS9XM1JFMGdP
            LzRjZ2krRzFwc2ZBczkvdVZVMTY5amJKOVlHaEhGdGhSd2lpRVJsR2xqOGVoSkc1
            aXJlc0h3MzVQUmdoUmlwL29hN0hxNkJXN1N1Yjc5RkFOb3hEK1NxK0tmWG4rYzNi
            NHdmWWllUStyRVgxY1JLMjdiRnpYU2Z6cHBXdzJrZWlNWU5tVUQzL2ZIN0pRb2tT
            dHpsOUdpdlJYekgyOTVTaGtHaEppNy9iYUdKVTV4Z0RVQmQ2N3FqaVY4NXFqN0Ey
            T1cvcmlwRittdVNnc1VHTkdJVjNTN0VQdlJ3R2tBM0t6bWxNbENlTnZzOFBiSWFF
            QWtYMFFCZ3EzbnBjVUYvV3YzS2RGdWRtcXgvcVVuVnltUjZRVmxjSkFEL3MwLzcv
            TjVkV1oyQzJuV2NBcWp6MGdYQUphRjF4eDFaTkpJVGs3bC92d0l6LzYxVXdSVjUz
            YnppQTVVdTF4dFBJMUVqU21McnhGb2JGd1d4VGwvUzdKYUs3Z0N3K05kYXBOc3ZI
            N0Uyb0czK1VYbXYzMk5LcHZMRE05amMwOFNCQlo3ZndUNHNJUFRENHNVYWsrcEpY
            ZFlQanNFQTNnMGNvUmJ5NkVyd0tWWkU2NzZRT0FDb0dpRmlhZWdZMFZuL3NCZHBi
            QjFoNGdYZlNIVVdvd2tQa0s5Qm9NUFY1WEZCSUw0Nk00Si9jeWZDaFFsK3pQRVZT
            U2RtUkovczNlNW5OSFh0U3Y4L2JPeVVjME1kOURERkRwTnUxR0djR1l2eTFGWlJo
            ZFFZSVk0blhwWVFxc0poa2REYnpiV0plOHc2N2V2VGwvcndGYVBMd3I1dklkdXdM
            UFFlbE5BQmVMNWR0cW93NkNQL3RwZTNlY2UyVDZjMnE5bEpjMnRLNkFVc3UvYUJn
            RHV2dGFiVmpvT0EyMGhSeElZZ1Y1Ym43VkQ4VXhSN3M4SE42V042UXVVaWlWTW5o
            NU52UktOdDR0cElYeEtqT1FOazE5KzFudEg2Y093Vzh6VnJYbXZvYTVnb1Bmbm04
            TVhIZS8vdXBKREVjVmVPcWgweGVxNEFYdmxBMjRnMTVtYTFzeWdYWWtXVHpRN0JJ
            TWpVYjViaXJTT2EyTmZjMit3NUdYOGhGajYwbDRrRDFuWFlhTzNDcnh3UWhaTjBq
            OTVQWTNvakxBRW9tWEtEblZERE9zK2VjM0VHNzVBRTJuZFRudWJMMlZIOTdxRmwx
            UmF6d1J1eHp5Yk5MS2s2eWFZYWFHMkhzK0lVVTNGQnZqZHF3cWcvUmJHNVhETnZr
            ZjNnd3Ayd2QvaStHUmthRU1OQTRqLy9jUlBjMlBIZFNoL0xxWHA4SlZ1L2VLS0hQ
            WGx5RjhEbzlCazlaYlR2ZWxWUGhnUzhQSVNjWGVvRG5HVzhnVmtjNEphS3E4M0xm
            OXpjQm9iM3RoOHByaEk3VzkveGtKZThhd3ZCdEV3VmIwbXRMU2MyWHJhQmhuWjcz
            M1A4TkI1c3NXSC9CcnBLN3pOcDFPOTljVVhmcHROcEJUZWlWSnFjQlFGRTVYcC9P
            Q2h5ajhuR3lDdDA0VDJ0bVJqQXdScjB4eVZBNDZsRTJMRmcwYjBDMHlEQnNNT3Np
            dHZsVkxJSGNJcWhlZXh5UmhzZ3BUOG5BWmhGQWk5MDdPQ21UTlRlVFlGdjU4bDM5
            VkVLWnA2M3prYlVBM0ZROFVlYmVWNzgrKzdKRlpCRzgrQnJSREdSZjVsWmx1SnBr
            UENkSlUycnh4S0ZmSUhQOFVlcGhJUlllbUdVSzZuZVNMS3VZNFZYemhmQUQ4UEdE
            UkRoa0ZyaTVCMCtySFVMbVhTVjdmYm0zWk5QS2pkeTQwNGJzM2VGS2h5MUhWTkZD
            YTV6YjI5UVJjV1lkVng4eDEwMkdpcnVUUm5WdXd0bXhHRFNvNUpjeEgwUXdXUQpM
            WjdxNkhQNlBsbVk2azRNRHFrVUFiYmg4c0lGUmM2TmR5N0tTNGlLUnVBCi0tLSBw
            a0dTMTQrZ1lSb2o3eGdabWNtVEoySS8rZlhUZVJUNlpna2hMcFFBRVlJCnsrjkSt
            adVRSU7x2olWBU1mXrcEh5tpA/1ejclezfIzMR4xjBSGjJUo6TF8ZSoUMMRdPPXV
            LXP+IueF+/UKs1M=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq182j3ewjp0rg2gfsanp9elcshzg9h5jpsqdxz24245fzz5fd366uksqvrq995x6kl0v53nevq4atfyhq53q98kl3sq4zf6uxpmh4sguvxwdg0p8dg6c6e45tjhymv63gnfltffzhsuf8gjhpp3l2caj75pgj7q8vtva25ejqckse8dxcmtxzryglf9dyqzst5mtcqaaenrhewk3rnp0z62kqrycrgyawgxn57t88mxxlpwv3tukryf9eh32vngzyeuzcvsa4za6kzf89qwxv3knmqhj9uzh9ds8n94yv8257q3dvluql30uy5ltgswgez5pxmkg6l2p53e7mn6xesy3ry48dez2ft2c23ewxde03mexfmc0mlsxu4q2n0qwxyreetz7npvjppzgmspqzlwf9gq7t3fcsu487xf06mas65kw9gru2skchuv9wcwzf89zhd52z8d44xu7sefxap2hqyyak8judkyzumvg2psxyvzmy8gkfz2qrz385xxljzwuut9vwwz2d6pd5044trh028fpqzcd8uuqwyv4gj8hv6vx3ktysgxw4tv9a83kae8mnqdcyvygfrtjedwrxgufv82ae5e8ru8txnxsmzadqaqy4yddpg7pjvw6gm437drvn9adv5mjnqx7wvjqj4tsmu0t99wwymel7g72qyvphygstan39f63z97azshhnreqdjrwc5j42e2xdwjyncq7vt9pe0y9qu43ywjacrw26zkfdvfnfvgmsxj967g6gd4xppem5m39smxzerkke8xcg4dzgxxgfg9f5peq0n6euzf6zsxj532k2cvlzc8q6m0t9x8gs8ll5gpvcnsmuq56stv5gru7d59uc3wpwfkespv3nec76jnyn7e79gzuevy96u2c2g7kg357ecv8qjge2sc6ragj9pq9yctev34djm5v02e2twkra7vs3rm6d7c2m6lcdkdm4pknkykc9quxtjrn9y5r42vg89jz49x3ga052wf2m6wglr5g7w53nzetzjudjx8ldxjgqp5c0yt9zfmx2zu76fkggn3rcugv035a0tzdyh79md77dh6kgqf9l5qrcrgk9cv9p9qks55ep8r9pcqnpmxcfy7ypr27zsh7upqle2kra6mv9aast4fe390sv3cv2hjdh3u4zf7upgqxg2wm9r0kswzhyt6rzjk33326vyk4amx92kzydnf9ccv0q6pcxg3nnp58tucw08fz6ym2d0ncvute9kgup7npd38x748egwdcv8czugdggg26uvl352w4znjcyze5u42xy8vc0fcajv0guhzq2vadfhcp4s0sz20dzntfw0hn6e4wm8h5ur5rq53g83ygxw4qez7amnnzf93skxmpdrc43v4en3au6z59y9xpsm9z3azv5thaxgph2fxewyx9d37r956g2nr5jn3msfqv4ssm2s39a3vcgd8sevl6deqysmhja5y2d5y0z7t0ak5xyfy4q557fxz2kgmgkq5mu60ya6eydfwzpf29vfklyll2f2de2hy2f79jx6xjwqt4fdxymyp2mcg7tw907hs2snfywfgagz5llfn4jd5pn74z6wtpgfqum4rssmpu2kqgtzyc3d4gcpqwdjsnwjzp4w2l5v9wnc6k5aw4q9z4wyencjtx3edwunfqn4tu9s2pqt8wl84y37qv5waukv78af0ywyz2redpmpkwzxu647gax95muz2s4fnydvtgh42vrlqqgulmt422zrjpmqvmxev5n7mku2tsmc599y2ym0sjwpacs8uztpzjyurgws390s2jxjzujw54usettx5uvf3q7wpqjkm55eqexddql87krt9wv2mnak5capzhk3lvs5ptafe9hex7v0znk76ma8yccuskv6y3stzzj2mh46w0cjmmuzf4yr96ecwtggvushzcltm3ss
    encrypted_regex: ^(opnsense|kanidm|oauth2_proxy|argocd)$
    lastmodified: "2026-09-09T22:56:29Z"
    mac: ENC[AES256_GCM,data:YbPeYRuIQbd9Qpnubpl+Sqgpp8CehzUEQ74JSudytnmocohoBk1AfhHiwi/jlqWcln4dd0IOlvw8YFZO6AiUX3RHNUFR55t9F1WPzdfB2xAl2CQ5Pl1L+MZu1PeS/0GaHT5tX6Vk139kFGqqShFfpJK/2/HGpTgxgHc9teo2R1E=,iv:LLYYiWxHEkRFmAwenBTIIOnRF/zHFrbsLfwn75ApmTg=,tag:gfPLr5Ib/3x5RkajqGgNcg==,type:str]
    version: 3.13.0
