apiVersion: ENC[AES256_GCM,data:EqA=,iv:6+pvH+O3vVGK9v7JWl/7CZXLpxAowcZxycln7Dl5bbY=,tag:RoC/Wsmya4xkXLKhCtCTPQ==,type:str]
kind: ENC[AES256_GCM,data:yO1+OVSc,iv:9uVT/E90mFJo1ff192XD7u9Ub6i5KP6z20r6vXxPp0U=,tag:nBTOEwZ6/2vqC2dWUXeJCg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:w3bys+Q9DJo4QW4N1yDJvkcxIq7zunowPQ==,iv:NK3Em/lTaBKCnB4A3nnK99E1dmco+TfdOA6IiQRMbAo=,tag:0v0VbmtkWyAiTP9QttbPxw==,type:str]
    annotations:
        description: ENC[AES256_GCM,data:LaNazdzw1GdS4E8WX2OSauolEC2OvinvBdtigktTnm8pYV7pG18H/66pu4Lr4A8fIMmr/TToZOShMDPOAZmK,iv:DVPxnaMTx3LHngeo9EyezL3R31FDB5ZU4kzXGKz4XVM=,tag:c6vTuRQMWslJfNVbE7ZLkQ==,type:str]
data:
    kanidm_idm_admin_password: ENC[AES256_GCM,data:P3QcE7jbCU37syBVaFRX4YR+bHu6E0SZlsixQZzT9FCzrRzCEPBrZ5YFwCKMn3Pt,iv:DPxRqDY3WHHvEcHyLC3+fmVEC0u/ZG+7f3luTAiPap0=,tag:0B0yVrpKg925BQjfjSrZEg==,type:str]
    tinyca_fingerprint: ENC[AES256_GCM,data:BhrboYISayP72UxXPOoIXQwwXkkQGEezkBpdxUBSmDtiLeZSxmQyMnLeoCdp9emcMSg4DdjvPvorg8eHE4LQdg==,iv:uGIKgRpgK+5k4dAC/4FoPJkOQJ9RSRHMTQcpgAzOUXM=,tag:EVulAbHEa+vY1K8K+bHRqA==,type:str]
    tinyca_url: ENC[AES256_GCM,data:hjG5h9yB75Ac6pgAoeUneM0PKeBzJZ4+4bE+qUCznnBqJUDI0w==,iv:YmT5Y8U9r2ni2Di6cLuBqhXxYxk6nbJwCov56KvFeno=,tag:2Gvq+VGFW2Gi3B+8zQ3HRA==,type:str]
    oauth2_proxy_client_secret: ENC[AES256_GCM,data:C47kOSg5JS2TxGa0V571RCzgP51uT+Ur0zF1U9AcWADJo4jv5Fg=,iv:hYG9iX7lFPYHqqkKgv+zTKO7efLKbYe6JufjzNQg9EQ=,tag:9p9vJcb5aoZj75Yweec9Dw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGNpdFErQ0Ez
            WEdFRVNMcThMNzc2STIyMWxFL3Iwc20rTmlzRisrbFJxZXcwdWZQc2xJSytLSnBo
            OE1tcmlFa29sb2ZtVzBIQnJQbkZsQ1paUG9ZbHh2RmhKZmlMcm44emZTT2RKb3Rs
            NkthYjBrSGdqdVlXL01oMWN6OE9CMEJOZ01wTkxOS0x0ZHAxcXNnRnIvRFd6YTJK
            T0s1Y1NObDU1ZzVNbkppeE55VWR3VHdIQ3ZsVFMyZEFRbnk2VzNtcERFWEVRcVVB
            TzBobHNnZWNWQUEwZ3EzTlFDSW9IN2NpbWxlMjNYbVhwZnB2TEZDRytFSHdxMDlT
            cUdJeEttTVdocnZLTnA5VUN1WGRKelQ3UysyeXVjcGd1blRETi9XUVpJaUVFbXpz
            YjJwRFlScXA3SXZwaHlvNVd4MFVoMWduR1crK0JpaEVtaE1YdWxMc3dXS0kyUnQ0
            S2xMV3RjL05tSDVueE03dEtia1FPQWk4Wng2dFpBYko5ejBQOFJiaThCdUp0M0Ux
            a1ZuRENoKzlVdE1vY1lTc0FiRTIrd1J0cUhrdDYwZENSTmF2bXJSaENGWUhGRmIr
            TTMySTFyYWlQdlJpUXJvTmNza1czNHVYR3V0aTc2b2x0R1lzMWcxMG54U3RQbkwy
            eFFQU0ZrcjQxQmtQWEJTS1hRVGVoQUpoU1B5TTAra0tOVWhlZVpFNktEOVpZT1A1
            MU5lUXIreHN1RUZud1Q1eWlxTitMYjNXc0lkSFlrbDFwQUY4S3ZhaEg1c3Y2b2Vq
            WkZuTXdnRUlZZkF5RktzQTk4TFgyR0hkZ1hqVEI1L05HeENmbFVQbnZINUdneGVD
            SU1QRjhBL3JJNUJiTW1FQTVwbWtXZzNwemdtaFZRZFdPUlRBcWVQNEpMZzE0Tm1w
            aWxOcVNrZW10TllsMk44bzU3OStBMitCM2ZzYitxM3l1T25QNHJ1VGZXVW9uUWNr
            amVDRW12RkV6TDFLYkJvTTJlalRkWUZhYU85UTNDbmFSREp4Zkd3Z0ZrMGZzRE00
            RUY4emF0NmNhbXVXTWxpMDNIdFdlOUtqZmMvdTcyWnJIYmp6T3REdEFIVVBOLzF2
            KzIwbm1PUGwrNlFFU0hCOG5MQzFNQkEwMjlOVEt6aldZQXFNZkJXSmVNeFFTV1kr
            Qi9NVHNrRnJrRnhaZkRHcjBEaVJ4cGhXeTdGY0lBaEttQ1plWmtXWVFvblBaWUVl
            YmRtanpZdE4wak03R2ROZGNzeEpZRUUxclJMamJTSURUcDUyVTUwK1U5UTZONzJr
            dEx2dFBuSEpFVjBYMHQ1Rmp3TnlOWkNiMDJGbFZBMkVRM056YUdVWlR6VzRNNDI2
            OUs1a1ptVmZsdmttT2ZtREE3MWJvOGFtZlRtQTZxdUhaRFFydWxMOEZOc1hsZFNy
            dmFrM1NFYlo2UXRCeWx3S2pkeXVCMllITHlrMVloNFcrSkJJb1hxQ1hrOFA1dFFi
            UTlkMTVMemVwc3ZESWk5K0RwSnF4a3FxMHdDRERQT09xR1g1cEZ4d0laRDhZSlRE
            dXpjaFBDS0V1VUZuYlUwNEw5S2gyVVJ1S3RtYjY3MHVVYVBTWmV6NlNvb2ZEajJZ
            MnhOM0JDOUl5VjB0RitkREc0Nlo3UmdkdDFaNkFyM3U2RDVnd2puczY3WXJGSEYx
            WlVkWVJBdHdwb0tudGV3NEhkTWt4OWR4WkVEUi9wSGNJdVpvMFJKNG9MR1ZMN2Za
            OTB5aThGajcyTTNjWUZGdmd3QXpsb2NqOUFuVGRrOTRIbWc1VFppbk1DSXFTY2hl
            bndLL1JDaUhVb1lidTJXdkZtUEs2WWptVWZUZGgrbysyUFMwNnRIc0ZhRTdlcC9W
            T0M4ejBPam05a3A5dzExMUdkSERpdHRrWGlGaUFRdm93OWFZTkg5S2wzL1lBWkc1
            QTNVKzBDUVVxbmJMbnFVZWFDaVA4YTFFcjZrSGV5d21KZnIzWFllRlYzMVNVZwpu
            SHlBZVhvT3ZNR0MwZ0NzcjZ4MkdUajVab2NlM2xYa0IwNkFiMTBCeVpvCi0tLSBz
            L2VkbkxFWXZJbVZlZ2NHa3F0bnVWRW91Mld5ZUl6QTF0dzNDaGRPTnJ3CqbYlONG
            RM9LhesYSG1/24dw1KMvUKTfFOdR4GX+Ge1kun4zy+z9ckTMAxUlMxSpOUrheCfO
            uDAWWGoyUzWgor8=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq182j3ewjp0rg2gfsanp9elcshzg9h5jpsqdxz24245fzz5fd366uksqvrq995x6kl0v53nevq4atfyhq53q98kl3sq4zf6uxpmh4sguvxwdg0p8dg6c6e45tjhymv63gnfltffzhsuf8gjhpp3l2caj75pgj7q8vtva25ejqckse8dxcmtxzryglf9dyqzst5mtcqaaenrhewk3rnp0z62kqrycrgyawgxn57t88mxxlpwv3tukryf9eh32vngzyeuzcvsa4za6kzf89qwxv3knmqhj9uzh9ds8n94yv8257q3dvluql30uy5ltgswgez5pxmkg6l2p53e7mn6xesy3ry48dez2ft2c23ewxde03mexfmc0mlsxu4q2n0qwxyreetz7npvjppzgmspqzlwf9gq7t3fcsu487xf06mas65kw9gru2skchuv9wcwzf89zhd52z8d44xu7sefxap2hqyyak8judkyzumvg2psxyvzmy8gkfz2qrz385xxljzwuut9vwwz2d6pd5044trh028fpqzcd8uuqwyv4gj8hv6vx3ktysgxw4tv9a83kae8mnqdcyvygfrtjedwrxgufv82ae5e8ru8txnxsmzadqaqy4yddpg7pjvw6gm437drvn9adv5mjnqx7wvjqj4tsmu0t99wwymel7g72qyvphygstan39f63z97azshhnreqdjrwc5j42e2xdwjyncq7vt9pe0y9qu43ywjacrw26zkfdvfnfvgmsxj967g6gd4xppem5m39smxzerkke8xcg4dzgxxgfg9f5peq0n6euzf6zsxj532k2cvlzc8q6m0t9x8gs8ll5gpvcnsmuq56stv5gru7d59uc3wpwfkespv3nec76jnyn7e79gzuevy96u2c2g7kg357ecv8qjge2sc6ragj9pq9yctev34djm5v02e2twkra7vs3rm6d7c2m6lcdkdm4pknkykc9quxtjrn9y5r42vg89jz49x3ga052wf2m6wglr5g7w53nzetzjudjx8ldxjgqp5c0yt9zfmx2zu76fkggn3rcugv035a0tzdyh79md77dh6kgqf9l5qrcrgk9cv9p9qks55ep8r9pcqnpmxcfy7ypr27zsh7upqle2kra6mv9aast4fe390sv3cv2hjdh3u4zf7upgqxg2wm9r0kswzhyt6rzjk33326vyk4amx92kzydnf9ccv0q6pcxg3nnp58tucw08fz6ym2d0ncvute9kgup7npd38x748egwdcv8czugdggg26uvl352w4znjcyze5u42xy8vc0fcajv0guhzq2vadfhcp4s0sz20dzntfw0hn6e4wm8h5ur5rq53g83ygxw4qez7amnnzf93skxmpdrc43v4en3au6z59y9xpsm9z3azv5thaxgph2fxewyx9d37r956g2nr5jn3msfqv4ssm2s39a3vcgd8sevl6deqysmhja5y2d5y0z7t0ak5xyfy4q557fxz2kgmgkq5mu60ya6eydfwzpf29vfklyll2f2de2hy2f79jx6xjwqt4fdxymyp2mcg7tw907hs2snfywfgagz5llfn4jd5pn74z6wtpgfqum4rssmpu2kqgtzyc3d4gcpqwdjsnwjzp4w2l5v9wnc6k5aw4q9z4wyencjtx3edwunfqn4tu9s2pqt8wl84y37qv5waukv78af0ywyz2redpmpkwzxu647gax95muz2s4fnydvtgh42vrlqqgulmt422zrjpmqvmxev5n7mku2tsmc599y2ym0sjwpacs8uztpzjyurgws390s2jxjzujw54usettx5uvf3q7wpqjkm55eqexddql87krt9wv2mnak5capzhk3lvs5ptafe9hex7v0znk76ma8yccuskv6y3stzzj2mh46w0cjmmuzf4yr96ecwtggvushzcltm3ss
    lastmodified: "2026-09-07T21:17:32Z"
    mac: ENC[AES256_GCM,data:h0XZJ7KYl3E3zHG1GdgB2WikMUUCy0WKqgVGpS9MjjSbZfnGGUdvrfNQ6CCjEWaEJxNeMqBT/vDqnX9zRya+ksIZ7AWIkubvCsCzdWpuHF+L+A5oCmAdvpB7B2MDm1CCfmrm8mFKEM2B7za+HiIIqYoY1Dee5hYpoRWPq4cLCNI=,iv:6egzosFYKvujramGPxqkMdbR9U/yP0gmRwGmut7L154=,tag:cJFjtDuCWvZW8uiVHGEhZg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
