apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: &name victoria-metrics-single
    repo: https://victoriametrics.github.io/helm-charts/
    version: 0.45.0
    releaseName: *name
    namespace: monitoring
    valuesFile: values.yaml
