---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zot-storage
  namespace: registry
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
