---
apiVersion: v1
kind: Service
metadata:
  name: zot
  namespace: registry
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: zot
  ports:
    - name: registry
      port: 5000
      targetPort: 5000
      protocol: TCP
