apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - virtualservice.yaml
helmCharts:
  - name: &name grafana
    repo: https://grafana.github.io/helm-charts
    version: 10.5.15
    releaseName: *name
    namespace: monitoring
    valuesFile: values.yaml
