apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: &name sops-secrets-operator
    repo: https://isindir.github.io/sops-secrets-operator/
    version: 0.28.1
    releaseName: *name
    namespace: *name
    valuesFile: values.yaml
