---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-ingress-tls
  namespace: istio-ingress
spec:
  secretName: istio-ingress-tls
  duration: 8760h
  renewBefore: 720h
  commonName: "*.opnsense.internal"
  dnsNames:
    - "*.opnsense.internal"
  usages:
    - server auth
  issuerRef:
    name: homelab-ca
    kind: ClusterIssuer
    group: cert-manager.io
